# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=768m -Dfile.encoding=UTF-8 -Djava.awt.headless=true
kotlin.daemon.jvm.options=-Xmx1024m -XX:MaxMetaspaceSize=384m
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=2
android.nonTransitiveRClass=true
android.builder.sdkDownload=true
kotlin.code.style=official
googleServices.missing.passthrough=true

