// Generated by tools/generate-component-items.py. Edit the JSON source.
package com.example.data

import com.example.model.WildRiftItem

object WildRiftComponentItemsData {
    val items: List<WildRiftItem> = listOf(
        WildRiftItem(
            id = "tear_of_the_goddess", name = "Lágrima de la diosa", namePt = "Lágrima da Deusa",
            category = "Básico", goldCost = 400,
            stats = "+200 Maná máximo",
            statsPt = "+200 Mana máximo",
            passive = "Asombro: Recuperas un 10% del maná gastado.\nCarga de maná: Aumenta el maná máximo en 5 cada vez que se gaste maná, hasta un máximo de 700 de maná adicional. Se activa hasta 3 veces cada 10 s. Solo se puede tener 1 objeto de Lágrima de la diosa.",
            passivePt = "Espanto: Recupera 10% do mana gasto.\nCarga de Mana: Aumenta o mana máximo em 5 sempre que mana é gasto, até um máximo de 700 de mana adicional. Pode ser ativada até 3 vezes a cada 10 s. Só é possível possuir 1 item de Lágrima da Deusa.", iconUrl = ""
        ),
        WildRiftItem(
            id = "dagger", name = "Daga", namePt = "Adaga",
            category = "Básico", goldCost = 400,
            stats = "+12% Velocidad de ataque",
            statsPt = "+12% Velocidade de ataque",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "long_sword", name = "Espada larga", namePt = "Espada Longa",
            category = "Básico", goldCost = 500,
            stats = "+12 Daño de ataque",
            statsPt = "+12 Dano de ataque",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "brawlers_gloves", name = "Guantes de pelea", namePt = "Luvas de Briga",
            category = "Básico", goldCost = 500,
            stats = "+10% Probabilidad de crítico",
            statsPt = "+10% Chance de acerto crítico",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "pickaxe", name = "Pico", namePt = "Picareta",
            category = "Nivel Medio", goldCost = 800,
            stats = "+20 Daño de ataque",
            statsPt = "+20 Dano de ataque",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "sheen", name = "Brillo", namePt = "Brilho",
            category = "Nivel Medio", goldCost = 800,
            stats = "+10 Velocidad de habilidades",
            statsPt = "+10 Aceleração de habilidade",
            passive = "Hoja encantada: Tras usar una habilidad, el siguiente ataque básico en los próximos 10 s inflige daño físico adicional equivalente al 100% del daño de ataque básico. Enfriamiento de 1,5 s. Inflige daño reducido contra estructuras.",
            passivePt = "Lâmina Encantada: Após usar uma habilidade, o próximo ataque básico nos próximos 10 s causa dano físico adicional equivalente a 100% do dano de ataque base. Tempo de recarga de 1,5 s. Causa dano reduzido contra estruturas.", iconUrl = ""
        ),
        WildRiftItem(
            id = "executioners_calling", name = "Llamada del verdugo", namePt = "Chamado do Carrasco",
            category = "Nivel Medio", goldCost = 800,
            stats = "+15 Daño de ataque",
            statsPt = "+15 Dano de ataque",
            passive = "Golpe devastador: Infligir daño físico a campeones enemigos aplica un 40% de heridas graves durante 3 s.",
            passivePt = "Golpe Devastador: Causar dano físico a campeões inimigos aplica 40% de Feridas Dolorosas por 3 s.", iconUrl = ""
        ),
        WildRiftItem(
            id = "phage", name = "Bacteriófago", namePt = "Fago",
            category = "Nivel Medio", goldCost = 1000,
            stats = "+150 Vida máxima • +15 Daño de ataque",
            statsPt = "+150 Vida máxima • +15 Dano de ataque",
            passive = "Furia: Al impactar, los ataques otorgan 20 de velocidad de movimiento durante 2 s. La bonificación no se acumula. Los campeones a distancia obtienen la mitad.",
            passivePt = "Fúria: Ao contato, os ataques concedem 20 de velocidade de movimento por 2 s. O bônus não se acumula. Campeões de ataque à distância recebem metade do valor.", iconUrl = ""
        ),
        WildRiftItem(
            id = "quicksilver_sash_mid_tier", name = "Fajín de mercurio", namePt = "Faixa de Mercúrio",
            category = "Nivel Medio", goldCost = 1100,
            stats = "+30 Resistencia mágica",
            statsPt = "+30 Resistência mágica",
            passive = "Fajín de mercurio: Elimina todas las debilitaciones de control de adversario que te hayan aplicado y otorga inmunidad contra el control de adversario durante 0,25 s. No se puede utilizar mientras te lanzan por los aires o te empujan.\nPerseverancia: Cuando termina el efecto de Fajín, otorga un 30% de tenacidad y un 30% de resistencia a las ralentizaciones durante 1,5 s. Enfriamiento de 60 s.",
            passivePt = "Faixa de Mercúrio: Remove todos os efeitos debilitantes de controle de grupo aplicados a você e concede imunidade a controle de grupo por 0,25 s. Não pode ser usada enquanto você estiver no ar ou sendo empurrado.\nPerseverança: Quando o efeito da Faixa termina, concede 30% de tenacidade e 30% de resistência a lentidão por 1,5 s. Tempo de recarga de 60 s.", iconUrl = ""
        ),
        WildRiftItem(
            id = "hearthbound_axe", name = "Hacha hogareña", namePt = "Machado Termestre",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+20 Daño de ataque • +15% Velocidad de ataque",
            statsPt = "+20 Dano de ataque • +15% Velocidade de ataque",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "vampiric_scepter", name = "Cetro vampírico", namePt = "Cetro Vampírico",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+20 Daño de ataque • +8% Robo de vida",
            statsPt = "+20 Dano de ataque • +8% Roubo de vida",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "last_whisper", name = "Últimas palabras", namePt = "Último Sussurro",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+15 Daño de ataque • +15% Penetración de armadura",
            statsPt = "+15 Dano de ataque • +15% Penetração de armadura",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "hexdrinker", name = "Sorbemaleficios", namePt = "Hexdrinker",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+20 Daño de ataque • +20 Resistencia mágica",
            statsPt = "+20 Dano de ataque • +20 Resistência mágica",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "caulfields_warhammer", name = "Martillo de guerra de Caulfield", namePt = "Martelo de Guerra de Caulfield",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+25 Daño de ataque • +10 Velocidad de habilidades",
            statsPt = "+25 Dano de ataque • +10 Aceleração de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "serrated_dirk", name = "Daga dentada", namePt = "Punhal Serrilhado",
            category = "Nivel Medio", goldCost = 1000,
            stats = "+20 Daño de ataque • +8 Penetración de armadura",
            statsPt = "+20 Dano de ataque • +8 Penetração de armadura",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "kircheis_shard", name = "Fragmento de Kircheis", namePt = "Fragmento de Kircheis",
            category = "Nivel Medio", goldCost = 800,
            stats = "+20% Velocidad de ataque",
            statsPt = "+20% Velocidade de ataque",
            passive = "Descarga: Inflige 40 de daño mágico adicional al dañar a un campeón enemigo. Enfriamiento de 25 s, que se reduce en 1 s por cada ataque.",
            passivePt = "Descarga: Causa 40 de dano mágico adicional ao causar dano a um campeão inimigo. Tempo de recarga de 25 s, reduzido em 1 s a cada ataque.", iconUrl = ""
        ),
        WildRiftItem(
            id = "recurve_bow", name = "Arco curvo", namePt = "Arco Recurvo",
            category = "Nivel Medio", goldCost = 900,
            stats = "+20% Velocidad de ataque",
            statsPt = "+20% Velocidade de ataque",
            passive = "Refuerzo: Los ataques infligen 15 de daño físico adicional al impactar.",
            passivePt = "Reforço: Os ataques causam 15 de dano físico adicional ao contato.", iconUrl = ""
        ),
        WildRiftItem(
            id = "noonquiver", name = "Carcaj del mediodía", namePt = "Aljava do Meio-Dia",
            category = "Nivel Medio", goldCost = 1300,
            stats = "+20 Daño de ataque • +15% Probabilidad de crítico",
            statsPt = "+20 Dano de ataque • +15% Chance de acerto crítico",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "zeal", name = "Fervor", namePt = "Zelo",
            category = "Nivel Medio", goldCost = 1400,
            stats = "+15% Probabilidad de crítico • +15% Velocidad de ataque • +4% Velocidad de movimiento",
            statsPt = "+15% Chance de acerto crítico • +15% Velocidade de ataque • +4% Velocidade de movimento",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "bf_sword", name = "Espadón", namePt = "Espada G. p. C.",
            category = "Nivel Medio", goldCost = 1500,
            stats = "+40 Daño de ataque",
            statsPt = "+40 Dano de ataque",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "revelation_ring", name = "Anillo de la revelación", namePt = "Anel da Revelação",
            category = "Básico", goldCost = 300,
            stats = "+5 Velocidad de habilidades",
            statsPt = "+5 Aceleração de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "ruby_crystal", name = "Cristal de rubí", namePt = "Cristal de Rubi",
            category = "Básico", goldCost = 500,
            stats = "+150 Vida máxima",
            statsPt = "+150 Vida máxima",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "amplifying_tome", name = "Tomo amplificador", namePt = "Tomo Amplificador",
            category = "Básico", goldCost = 500,
            stats = "+20 Poder de habilidad",
            statsPt = "+20 Poder de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "forbidden_idol", name = "Ídolo prohibido", namePt = "Ídolo Proibido",
            category = "Nivel Medio", goldCost = 700,
            stats = "+25% Regeneración de maná • +6% Poder de curaciones y escudos",
            statsPt = "+25% Regeneração de mana • +6% Poder de cura e escudo",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "blasting_wand", name = "Vara explosiva", namePt = "Varinha Explosiva",
            category = "Nivel Medio", goldCost = 800,
            stats = "+40 Poder de habilidad",
            statsPt = "+40 Poder de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "bandleglass_mirror", name = "Espejo de cristal de Bandle", namePt = "Espelho de Vidro de Bandópolis",
            category = "Nivel Medio", goldCost = 900,
            stats = "+20 Poder de habilidad • +50% Regeneración de maná • +10 Velocidad de habilidades",
            statsPt = "+20 Poder de habilidade • +50% Regeneração de mana • +10 Aceleração de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "fated_ashes", name = "Cenizas predestinadas", namePt = "Cinzas Predestinadas",
            category = "Nivel Medio", goldCost = 900,
            stats = "+40 Poder de habilidad",
            statsPt = "+40 Poder de habilidade",
            passive = "Inflamar: Las habilidades infligen 5 de daño mágico adicional durante 3 s; infligen 15 de daño adicional a monstruos.",
            passivePt = "Inflamar: As habilidades causam 5 de dano mágico adicional por 3 s; causam 15 de dano adicional a monstros.", iconUrl = ""
        ),
        WildRiftItem(
            id = "fiendish_codex", name = "Códice diabólico", namePt = "Códex Demoníaco",
            category = "Nivel Medio", goldCost = 900,
            stats = "+25 Poder de habilidad • +10 Velocidad de habilidades",
            statsPt = "+25 Poder de habilidade • +10 Aceleração de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "oblivion_orb", name = "Orbe del olvido", namePt = "Orbe do Oblívio",
            category = "Nivel Medio", goldCost = 900,
            stats = "+35 Poder de habilidad",
            statsPt = "+35 Poder de habilidade",
            passive = "Heridas graves: Infligir daño mágico aplica un 40% de heridas graves durante 3 s.",
            passivePt = "Feridas Dolorosas: Causar dano mágico aplica 40% de Feridas Dolorosas por 3 s.", iconUrl = ""
        ),
        WildRiftItem(
            id = "aether_wisp", name = "Brisa de éter", namePt = "Éter Fogo",
            category = "Nivel Medio", goldCost = 950,
            stats = "+35 Poder de habilidad • +4% Velocidad de movimiento",
            statsPt = "+35 Poder de habilidade • +4% Velocidade de movimento",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "void_amethyst", name = "Amatista del Vacío", namePt = "Ametista do Vazio",
            category = "Nivel Medio", goldCost = 1000,
            stats = "+20 Poder de habilidad • +10% Penetración mágica",
            statsPt = "+20 Poder de habilidade • +10% Penetração mágica",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "kindlegem", name = "Gema avivadora", namePt = "Gema Ardente",
            category = "Nivel Medio", goldCost = 1000,
            stats = "+175 Vida máxima • +10 Velocidad de habilidades",
            statsPt = "+175 Vida máxima • +10 Aceleração de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "catalyst_of_aeons", name = "Catalizador de eones", namePt = "Catalisador das Eras",
            category = "Nivel Medio", goldCost = 1100,
            stats = "+200 Vida máxima • +300 Maná máximo",
            statsPt = "+200 Vida máxima • +300 Mana máximo",
            passive = "Eternidad: Restaura maná equivalente a un 15% del daño recibido y regenera vida equivalente a un 20% del maná utilizado, hasta un máximo de 15 de vida por lanzamiento.",
            passivePt = "Eternidade: Restaura mana equivalente a 15% do dano recebido e regenera vida equivalente a 20% do mana usado, até um máximo de 15 de vida por conjuração.", iconUrl = ""
        ),
        WildRiftItem(
            id = "hextech_alternator", name = "Alternador hextech", namePt = "Alternador Hextec",
            category = "Nivel Medio", goldCost = 1100,
            stats = "+45 Poder de habilidad",
            statsPt = "+45 Poder de habilidade",
            passive = "Revolucionado: Las habilidades de daño y los ataques potenciados infligen de 25 a 60 de daño mágico adicional. Enfriamiento de 20 s.",
            passivePt = "Revitalizado: As habilidades de dano e os ataques fortalecidos causam de 25 a 60 de dano mágico adicional. Tempo de recarga de 20 s.", iconUrl = ""
        ),
        WildRiftItem(
            id = "lost_chapter", name = "Capítulo perdido", namePt = "Capítulo Perdido",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+35 Poder de habilidad • +200 Maná máximo • +10 Velocidad de habilidades",
            statsPt = "+35 Poder de habilidade • +200 Mana máximo • +10 Aceleração de habilidade",
            passive = "Iluminar: Al subir de nivel, recupera un 20% del maná máximo a lo largo de 3 s.",
            passivePt = "Iluminar: Ao subir de nível, recupera 20% do mana máximo ao longo de 3 s.", iconUrl = ""
        ),
        WildRiftItem(
            id = "haunting_guise", name = "Disfraz encantado", namePt = "Máscara Assustadora",
            category = "Nivel Medio", goldCost = 1300,
            stats = "+200 Vida máxima • +30 Poder de habilidad",
            statsPt = "+200 Vida máxima • +30 Poder de habilidade",
            passive = "Demencia: Inflige un 2% de daño adicional por cada segundo en combate contra campeones, hasta un máximo de un 6%.",
            passivePt = "Demência: Causa 2% de dano adicional a cada segundo em combate contra campeões, até um máximo de 6%.", iconUrl = ""
        ),
        WildRiftItem(
            id = "needlessly_large_rod", name = "Vara innecesariamente grande", namePt = "Bastão Desnecessariamente Grande",
            category = "Nivel Medio", goldCost = 1400,
            stats = "+65 Poder de habilidad",
            statsPt = "+65 Poder de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "seekers_armguard", name = "Brazalete de la buscadora", namePt = "Braçadeira da Caçadora",
            category = "Nivel Medio", goldCost = 1400,
            stats = "+20 Armadura • +35 Poder de habilidad",
            statsPt = "+20 Armadura • +35 Poder de habilidade",
            passive = "Éstasis: Te vuelve invulnerable e inalcanzable durante 2,5 s, sin permitirte moverte, atacar ni lanzar hechizos. Enfriamiento de 150 s.",
            passivePt = "Estase: Torna você invulnerável e inalvejável por 2,5 s, sem permitir movimento, ataques ou conjuração de feitiços. Tempo de recarga de 150 s.", iconUrl = ""
        ),
        WildRiftItem(
            id = "verdant_barrier", name = "Barrera frondosa", namePt = "Barreira Verdejante",
            category = "Nivel Medio", goldCost = 1600,
            stats = "+40 Poder de habilidad • +25 Resistencia mágica",
            statsPt = "+40 Poder de habilidade • +25 Resistência mágica",
            passive = "Anular: Otorga un escudo de hechizos que bloquea la siguiente habilidad enemiga. Enfriamiento de 65 s.",
            passivePt = "Anular: Concede um escudo de feitiço que bloqueia a próxima habilidade inimiga. Tempo de recarga de 65 s.", iconUrl = ""
        ),
        WildRiftItem(
            id = "mejais_soulstealer", name = "Robaalmas de Mejai", namePt = "Ladrão de Almas de Mejai",
            category = "Nivel Medio", goldCost = 1800,
            stats = "+70 Vida máxima • +25 Poder de habilidad",
            statsPt = "+70 Vida máxima • +25 Poder de habilidade",
            passive = "Gloria: Obtienes hasta 30 acumulaciones por asesinatos y asistencias. Pierdes 10 acumulaciones al morir.\nTerror: Otorga 5 de poder de habilidad por cada acumulación de Gloria. Con 10 o más acumulaciones, otorga un 10% de velocidad de movimiento.",
            passivePt = "Glória: Recebe até 30 acúmulos por abates e assistências. Perde 10 acúmulos ao morrer.\nTerror: Concede 5 de poder de habilidade por acúmulo de Glória. Com 10 ou mais acúmulos, concede 10% de velocidade de movimento.", iconUrl = ""
        ),
        WildRiftItem(
            id = "cloth_armor", name = "Armadura de tela", namePt = "Armadura de Pano",
            category = "Básico", goldCost = 500,
            stats = "+20 Armadura",
            statsPt = "+20 Armadura",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "null_magic_mantle", name = "Manto de anulación de magia", namePt = "Manto Anula-Magia",
            category = "Básico", goldCost = 500,
            stats = "+20 Resistencia mágica",
            statsPt = "+20 Resistência mágica",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "chain_vest", name = "Chaleco de cadenas", namePt = "Cota de Malha",
            category = "Nivel Medio", goldCost = 900,
            stats = "+40 Armadura",
            statsPt = "+40 Armadura",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "winged_moonplate", name = "Armadura lunar alada", namePt = "Placa Lunar Alada",
            category = "Nivel Medio", goldCost = 900,
            stats = "+150 Vida máxima • +4% Velocidad de movimiento",
            statsPt = "+150 Vida máxima • +4% Velocidade de movimento",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "negatron_cloak", name = "Capa negatrón", namePt = "Capa Negatron",
            category = "Nivel Medio", goldCost = 900,
            stats = "+40 Resistencia mágica",
            statsPt = "+40 Resistência mágica",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "giants_belt", name = "Cinturón de gigante", namePt = "Cinto do Gigante",
            category = "Nivel Medio", goldCost = 1000,
            stats = "+300 Vida máxima",
            statsPt = "+300 Vida máxima",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "bramble_vest", name = "Chaleco de zarzas", namePt = "Colete Espinhoso",
            category = "Nivel Medio", goldCost = 1000,
            stats = "",
            statsPt = "",
            passive = "Refleja daño y reduce la curación enemiga.",
            passivePt = "Reflete dano e reduz a cura inimiga.", iconUrl = ""
        ),
        WildRiftItem(
            id = "glacial_shroud", name = "Sudario glacial", namePt = "Proteção Glacial",
            category = "Nivel Medio", goldCost = 1000,
            stats = "+20 Armadura • +150 Maná máximo • +10 Velocidad de habilidades",
            statsPt = "+20 Armadura • +150 Mana máximo • +10 Aceleração de habilidade",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
        WildRiftItem(
            id = "wardens_mail", name = "Malla del guardián", namePt = "Armadura de Guarda",
            category = "Nivel Medio", goldCost = 1050,
            stats = "+35 Armadura",
            statsPt = "+35 Armadura",
            passive = "Acero frío: Reduce un 15% la velocidad de ataque del enemigo durante 1,5 s al recibir un ataque.",
            passivePt = "Aço Frio: Reduz em 15% a velocidade de ataque do inimigo por 1,5 s ao receber um ataque.", iconUrl = ""
        ),
        WildRiftItem(
            id = "spectres_cowl", name = "Hábito del espectro", namePt = "Capuz do Espectro",
            category = "Nivel Medio", goldCost = 1100,
            stats = "+175 Vida máxima • +20 Resistencia mágica",
            statsPt = "+175 Vida máxima • +20 Resistência mágica",
            passive = "Visita espectral: Otorga un 150% de regeneración de vida durante 10 s al recibir daño de un campeón.",
            passivePt = "Visita Espectral: Concede 150% de regeneração de vida por 10 s ao receber dano de um campeão.", iconUrl = ""
        ),
        WildRiftItem(
            id = "bamis_cinder", name = "Rescoldo de Bami", namePt = "Brasa de Bami",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+250 Vida máxima • +5 Velocidad de habilidades",
            statsPt = "+250 Vida máxima • +5 Aceleração de habilidade",
            passive = "Cenizas: Inflige de 10 a 20 de daño mágico por segundo a enemigos cercanos. Inflige un 115% de daño a súbditos y monstruos.",
            passivePt = "Cinzas: Causa de 10 a 20 de dano mágico por segundo a inimigos próximos. Causa 115% de dano a tropas e monstros.", iconUrl = ""
        ),
        WildRiftItem(
            id = "jaurims_fist", name = "Puño de Jaurim", namePt = "Punho de Jaurim",
            category = "Nivel Medio", goldCost = 1200,
            stats = "+200 Vida máxima • +15 Daño de ataque",
            statsPt = "+200 Vida máxima • +15 Dano de ataque",
            passive = "",
            passivePt = "", iconUrl = ""
        ),
    )

    val sectionItemIds: Map<String, Map<String, List<String>>> = mapOf(
        "Luchador" to mapOf(
            "Básico" to listOf("tear_of_the_goddess", "dagger", "long_sword", "brawlers_gloves"),
            "Nivel Medio" to listOf("pickaxe", "sheen", "executioners_calling", "phage", "quicksilver_sash_mid_tier", "hearthbound_axe", "vampiric_scepter", "last_whisper", "hexdrinker", "caulfields_warhammer"),
        ),
        "Asesino" to mapOf(
            "Básico" to listOf("tear_of_the_goddess", "long_sword", "brawlers_gloves"),
            "Nivel Medio" to listOf("pickaxe", "sheen", "executioners_calling", "serrated_dirk", "quicksilver_sash_mid_tier", "last_whisper", "caulfields_warhammer"),
        ),
        "Tirador" to mapOf(
            "Básico" to listOf("tear_of_the_goddess", "dagger", "long_sword", "brawlers_gloves"),
            "Nivel Medio" to listOf("pickaxe", "sheen", "kircheis_shard", "executioners_calling", "recurve_bow", "quicksilver_sash_mid_tier", "hearthbound_axe", "vampiric_scepter", "last_whisper", "caulfields_warhammer", "noonquiver", "zeal", "bf_sword"),
        ),
        "Mágico" to mapOf(
            "Básico" to listOf("revelation_ring", "tear_of_the_goddess", "ruby_crystal", "amplifying_tome"),
            "Nivel Medio" to listOf("forbidden_idol", "blasting_wand", "sheen", "bandleglass_mirror", "fated_ashes", "fiendish_codex", "oblivion_orb", "aether_wisp", "void_amethyst", "kindlegem", "catalyst_of_aeons", "hextech_alternator", "lost_chapter", "haunting_guise", "needlessly_large_rod", "seekers_armguard", "verdant_barrier", "mejais_soulstealer"),
        ),
        "Defensa" to mapOf(
            "Básico" to listOf("tear_of_the_goddess", "ruby_crystal", "cloth_armor", "null_magic_mantle"),
            "Nivel Medio" to listOf("sheen", "chain_vest", "winged_moonplate", "negatron_cloak", "kindlegem", "giants_belt", "bramble_vest", "glacial_shroud", "wardens_mail", "catalyst_of_aeons", "quicksilver_sash_mid_tier", "spectres_cowl", "bamis_cinder", "jaurims_fist", "seekers_armguard", "verdant_barrier"),
        ),
        "Apoyo" to mapOf(
            "Básico" to listOf(),
            "Nivel Medio" to listOf("forbidden_idol", "blasting_wand", "bandleglass_mirror", "fiendish_codex", "oblivion_orb", "chain_vest", "negatron_cloak", "aether_wisp", "void_amethyst", "kindlegem", "giants_belt", "bramble_vest", "glacial_shroud", "wardens_mail", "spectres_cowl"),
        ),
    )

    private val byId = items.associateBy { it.id }

    fun getItems(section: String, level: String): List<WildRiftItem> =
        sectionItemIds.entries.firstOrNull { it.key.equals(section, ignoreCase = true) }
            ?.value?.entries?.firstOrNull { it.key.equals(level, ignoreCase = true) }
            ?.value.orEmpty().map { byId.getValue(it) }
}
