package com.example.util

/** Editorial relationships reviewed on 2026-09-30; counts are caps, never padding targets.
 * Source and category provenance: docs/matchup-reference-audit.json.
 */
object ReviewedMatchupReferences {
    data class Reference(val counters: List<String>, val synergies: List<String>, val advantages: List<String> = emptyList())
    val byChampion: Map<String, Reference> = mapOf(
        "aatrox" to Reference(listOf("Fiora", "Malphite", "Ambessa"), listOf("Jarvan IV", "Syndra", "Leona")),
        "ahri" to Reference(listOf("Annie", "Syndra", "Aurelion Sol"), listOf("Ornn", "Rengar", "Thresh")),
        "akali" to Reference(listOf("Galio", "Lissandra", "Twisted Fate"), listOf("Shen", "Amumu", "Rakan")),
        "akshan" to Reference(listOf("Yasuo", "Orianna", "Lissandra"), listOf("Shen", "Nunu y Willump", "Rakan")),
        "alistar" to Reference(listOf("Janna", "Morgana", "Soraka"), listOf("Yasuo", "Samira", "Corki")),
        "ambessa" to Reference(listOf("Jayce", "Malphite", "Renekton"), listOf("Cho'Gath", "Syndra", "Thresh")),
        "amumu" to Reference(listOf("Gwen", "Nunu y Willump", "Olaf"), listOf("Akali", "Galio", "Miss Fortune")),
        "annie" to Reference(listOf("Syndra", "Irelia", "Lissandra"), listOf("Rumble", "Viego", "Thresh")),
        "ashe" to Reference(listOf("Caitlyn", "Draven", "Lucian"), listOf("Leona", "Nautilus", "Braum")),
        "aurelion_sol" to Reference(listOf("Yone", "Kassadin", "Akshan"), listOf("Camille", "Vi", "Bardo")),
        "aurora" to Reference(listOf("Vex", "Zed", "Irelia"), listOf("Shen", "Amumu", "Rell")),
        "bard" to Reference(listOf("Blitzcrank", "Senna", "Thresh"), listOf("Ashe", "Caitlyn", "Xayah")),
        "blitzcrank" to Reference(listOf("Nautilus", "Braum", "Alistar"), listOf("Xayah", "Draven", "Tristana")),
        "brand" to Reference(listOf("Syndra", "Zyra", "Hwei"), listOf("Camille", "Lee Sin", "Leona")),
        "braum" to Reference(listOf("Senna", "Rakan", "Zilean"), listOf("Tristana", "Lucian", "Yunara")),
        "caitlyn" to Reference(listOf("Sivir", "Ezreal", "Miss Fortune"), listOf("Nami", "Milio", "Bardo")),
        "camille" to Reference(listOf("Malphite", "Fiora", "Mordekaiser"), listOf("Vi", "Jarvan IV", "Galio")),
        "cho_gath" to Reference(listOf("Teemo", "Gwen", "Fiora"), listOf("Nocturne", "Yasuo", "Amumu")),
        "corki" to Reference(listOf("Kog'Maw", "Miss Fortune", "Caitlyn"), listOf("Nautilus", "Alistar", "Leona")),
        "darius" to Reference(listOf("Dr. Mundo", "Malphite", "Ornn"), listOf("Lillia", "Twisted Fate", "Thresh")),
        "diana" to Reference(listOf("Vex", "Galio", "Irelia"), listOf("Lee Sin", "Rakan", "Galio")),
        "dr_mundo" to Reference(listOf("Riven", "Gwen", "Fiora"), listOf("Ryze", "Olaf", "Leona")),
        "draven" to Reference(listOf("Caitlyn", "Samira", "Kog'Maw"), listOf("Nautilus", "Pyke", "Thresh")),
        "ekko" to Reference(listOf("Vex", "Irelia", "Lissandra"), listOf("Amumu", "Nami", "Shen")),
        "evelynn" to Reference(listOf("Rengar", "Twisted Fate", "Lee Sin"), listOf("Shen", "Ahri", "Veigar")),
        "ezreal" to Reference(listOf("Draven", "Miss Fortune", "Samira"), listOf("Yuumi", "Braum", "Bardo")),
        "fiddlesticks" to Reference(listOf("Nocturne", "Aatrox", "Alistar"), listOf("Galio", "Alistar", "Leona")),
        "fiora" to Reference(listOf("Rumble", "Malphite", "Poppy"), listOf("Soraka", "Lulu", "Zilean")),
        "fizz" to Reference(listOf("Galio", "Lissandra", "Vex"), listOf("Nautilus", "Leona", "Jarvan IV")),
        "galio" to Reference(listOf("Morgana", "Ahri", "Swain"), listOf("Amumu", "Jarvan IV", "Camille")),
        "garen" to Reference(listOf("Vayne", "Rumble", "Camille"), listOf("Zilean", "Nocturne", "Wukong")),
        "gnar" to Reference(listOf("Irelia", "Malphite", "Ornn"), listOf("Jarvan IV", "Nocturne", "Vi")),
        "gragas" to Reference(listOf("Amumu", "Nocturne", "Lillia"), listOf("Yasuo", "Bardo", "Ryze")),
        "graves" to Reference(listOf("Rammus", "Amumu", "Aatrox"), listOf("Janna", "Nami", "Nautilus")),
        "gwen" to Reference(listOf("Fiora", "Tryndamere", "Riven"), listOf("Rell", "Rakan", "Nautilus")),
        "hecarim" to Reference(listOf("Maestro Yi", "Kindred", "Graves"), listOf("Karma", "Zilean", "Nautilus")),
        "heimerdinger" to Reference(listOf("Zed", "Yasuo", "Irelia"), listOf("Amumu", "Jarvan IV", "Leona")),
        "hwei" to Reference(listOf("Kassadin", "Zed", "Fizz", "Yone", "Yasuo", "Morgana"), listOf(), listOf("Kennen", "Brand", "Aurelion Sol", "Annie", "Orianna", "Lissandra")),
        "irelia" to Reference(listOf("Malphite", "Wukong", "Poppy"), listOf("Xin Zhao", "Jarvan IV", "Nautilus")),
        "janna" to Reference(listOf("Blitzcrank", "Senna", "Sona"), listOf("Draven", "Jhin", "Lucian")),
        "jarvan_iv" to Reference(listOf("Rammus", "Maestro Yi", "Amumu"), listOf("Orianna", "Lissandra", "Miss Fortune")),
        "jax" to Reference(listOf("Poppy", "Teemo", "Rumble"), listOf("Lulu", "Janna", "Zilean")),
        "jayce" to Reference(listOf("Syndra", "Galio", "Irelia"), listOf("Jarvan IV", "Vi", "Lee Sin")),
        "jhin" to Reference(listOf("Draven", "Ashe", "Lucian"), listOf("Zyra", "Karma", "Rakan")),
        "jinx" to Reference(listOf("Jhin", "Miss Fortune", "Kog'Maw"), listOf("Lulu", "Janna", "Milio")),
        "k_sante" to Reference(listOf("Ambessa", "Vayne", "Garen"), listOf("Shyvana", "Maestro Yi", "Warwick")),
        "kai_sa" to Reference(listOf("Caitlyn", "Draven", "Kog'Maw"), listOf("Lulu", "Nautilus", "Alistar")),
        "kalista" to Reference(listOf("Ashe", "Kog'Maw", "Caitlyn"), listOf("Alistar", "Nautilus", "Thresh")),
        "karma" to Reference(listOf("Pyke", "Nami", "Bardo"), listOf("Lucian", "Ezreal", "Draven")),
        "kassadin" to Reference(listOf("Zed", "Yasuo", "Jayce"), listOf("Jarvan IV", "Nocturne", "Vi")),
        "katarina" to Reference(listOf("Vex", "Zed", "Lissandra"), listOf("Amumu", "Jarvan IV", "Alistar")),
        "kayle" to Reference(listOf("Syndra", "Viktor", "Ryze"), listOf("Lulu", "Zilean", "Soraka")),
        "kayn" to Reference(listOf("Maestro Yi", "Kindred", "Rammus"), listOf("Zilean", "Shen", "Malphite")),
        "kennen" to Reference(listOf("Gnar", "Nasus", "Wukong"), listOf("Orianna", "Jarvan IV", "Amumu")),
        "kha_zix" to Reference(listOf("Rammus", "Kindred", "Maestro Yi"), listOf("Shen", "Annie", "Zilean")),
        "kindred" to Reference(listOf("Rammus", "Xin Zhao", "Lillia"), listOf("Galio", "Malphite", "Lulu")),
        "kog_maw" to Reference(listOf("Ashe", "Caitlyn", "Vayne"), listOf("Lulu", "Milio", "Nami")),
        "lee_sin" to Reference(listOf("Rammus", "Lillia", "Nocturne"), listOf("Nautilus", "Yasuo", "Ahri")),
        "leona" to Reference(listOf("Galio", "Morgana", "Janna"), listOf("Ashe", "Lucian", "Samira")),
        "lillia" to Reference(listOf("Evelynn", "Vi", "Maestro Yi"), listOf("Seraphine", "Rakan", "Karma")),
        "lissandra" to Reference(listOf("Morgana", "Kassadin", "Galio"), listOf("Vi", "Viego", "Galio")),
        "lucian" to Reference(listOf("Caitlyn", "Kog'Maw", "Ashe"), listOf("Nami", "Braum", "Rakan")),
        "lulu" to Reference(listOf("Blitzcrank", "Senna", "Bardo"), listOf("Jinx", "Vayne", "Kog'Maw")),
        "lux" to Reference(listOf("Pyke", "Nami", "Karma"), listOf("Jhin", "Caitlyn", "Varus")),
        "malphite" to Reference(listOf("Rumble", "Mordekaiser", "Gwen"), listOf("Yasuo", "Orianna", "Annie")),
        "maokai" to Reference(listOf("Galio", "Braum", "Leona"), listOf("Draven", "Vayne", "Caitlyn")),
        "master_yi" to Reference(listOf("Rammus", "Viego", "Evelynn"), listOf("Zilean", "Lulu", "Karma")),
        "mel" to Reference(listOf("Irelia", "Yone", "Syndra"), listOf("Jarvan IV", "Leona", "Ornn")),
        "milio" to Reference(listOf("Blitzcrank", "Sona", "Bardo"), listOf("Kog'Maw", "Caitlyn", "Vayne")),
        "miss_fortune" to Reference(listOf("Smolder", "Jhin", "Caitlyn"), listOf("Leona", "Nautilus", "Rakan")),
        "mordekaiser" to Reference(listOf("Fiora", "Irelia", "Rumble"), listOf("Amumu", "Rammus", "Zilean")),
        "morgana" to Reference(listOf("Soraka", "Karma", "Zyra"), listOf("Draven", "Caitlyn", "Ashe")),
        "nami" to Reference(listOf("Pyke", "Blitzcrank", "Braum"), listOf("Lucian", "Caitlyn", "Ezreal")),
        "nasus" to Reference(listOf("Garen", "Camille", "Wukong"), listOf("Zilean", "Karma", "Lulu")),
        "nautilus" to Reference(listOf("Bardo", "Janna", "Morgana"), listOf("Draven", "Samira", "Miss Fortune")),
        "nidalee" to Reference(listOf("Maestro Yi", "Rengar", "Galio"), listOf("Nautilus", "Leona", "Renekton")),
        "nilah" to Reference(listOf("Rammus", "Amumu", "Kha'Zix"), listOf("Soraka", "Lulu", "Zilean")),
        "nocturne" to Reference(listOf("Rammus", "Maestro Yi", "Viego"), listOf("Orianna", "Ornn", "Shen")),
        "norra" to Reference(listOf("Kassadin", "Zed", "Yasuo"), listOf("Amumu", "Jarvan IV", "Leona")),
        "nunu_willump" to Reference(listOf("Lillia", "Evelynn", "Morgana"), listOf("Yasuo", "Camille", "Rakan")),
        "olaf" to Reference(listOf("Kindred", "Lillia", "Maestro Yi"), listOf("Lulu", "Soraka", "Leona")),
        "orianna" to Reference(listOf("Irelia", "Yasuo", "Syndra"), listOf("Nocturne", "Amumu", "Alistar")),
        "ornn" to Reference(listOf("Fiora", "Camille", "Shen"), listOf("Yasuo", "Viego", "Nocturne")),
        "pantheon" to Reference(listOf("Tryndamere", "Rammus", "Amumu"), listOf("Shen", "Twisted Fate", "Galio")),
        "poppy" to Reference(listOf("Ambessa", "Teemo", "Mordekaiser"), listOf("Yasuo", "Orianna", "Ashe")),
        "pyke" to Reference(listOf("Braum", "Maokai", "Soraka"), listOf("Samira", "Lucian", "Kai'Sa")),
        "rakan" to Reference(listOf("Galio", "Rell", "Nautilus"), listOf("Xayah", "Samira", "Kai'Sa")),
        "rammus" to Reference(listOf("Amumu", "Lillia", "Nunu y Willump"), listOf("Annie", "Sivir", "Camille")),
        "rell" to Reference(listOf("Janna", "Alistar", "Braum"), listOf("Samira", "Kai'Sa", "Lucian")),
        "renekton" to Reference(listOf("Gnar", "Teemo", "Mordekaiser"), listOf("Vi", "Rammus", "Hecarim")),
        "rengar" to Reference(listOf("Kindred", "Rammus", "Maestro Yi"), listOf("Shen", "Orianna", "Leona")),
        "riven" to Reference(listOf("Renekton", "Darius", "Wukong"), listOf("Yasuo", "Nidalee", "Leona")),
        "rumble" to Reference(listOf("Renekton", "Ornn", "Ambessa"), listOf("Jarvan IV", "Amumu", "Leona")),
        "ryze" to Reference(listOf("Kassadin", "Viktor", "Syndra"), listOf("Rakan", "Viego", "Leona")),
        "samira" to Reference(listOf("Kog'Maw", "Miss Fortune", "Caitlyn"), listOf("Nautilus", "Rell", "Leona")),
        "senna" to Reference(listOf("Blitzcrank", "Pyke", "Nautilus"), listOf("Jhin", "Miss Fortune", "Ashe")),
        "seraphine" to Reference(listOf("Pyke", "Braum", "Blitzcrank"), listOf("Ashe", "Miss Fortune", "Ezreal")),
        "sett" to Reference(listOf("Renekton", "Mordekaiser", "Aatrox"), listOf("Galio", "Amumu", "Vi")),
        "shen" to Reference(listOf("Fiora", "Renekton", "Gnar"), listOf("Nocturne", "Evelynn", "Kha'Zix")),
        "shyvana" to Reference(listOf("Rammus", "Lillia", "Maestro Yi"), listOf("Shen", "Zilean", "Lulu")),
        "singed" to Reference(listOf("Ambessa", "Fiora", "Camille"), listOf("Zilean", "Shen", "Alistar")),
        "sion" to Reference(listOf("Renekton", "Fiora", "Gwen"), listOf("Yasuo", "Nocturne", "Nautilus")),
        "sivir" to Reference(listOf("Kog'Maw", "Smolder", "Vayne"), listOf("Lulu", "Milio", "Karma")),
        "skarner" to Reference(listOf("Lillia", "Olaf", "Maestro Yi"), listOf("Miss Fortune", "Annie", "Lissandra")),
        "smolder" to Reference(listOf("Draven", "Lucian", "Caitlyn"), listOf("Braum", "Milio", "Leona")),
        "sona" to Reference(listOf("Blitzcrank", "Pyke", "Bardo"), listOf("Ashe", "Jhin", "Vayne")),
        "soraka" to Reference(listOf("Blitzcrank", "Nami", "Bardo"), listOf("Caitlyn", "Jinx", "Vayne")),
        "swain" to Reference(listOf("Brand", "Syndra", "Orianna"), listOf("Leona", "Nautilus", "Amumu")),
        "syndra" to Reference(listOf("Irelia", "Yasuo", "Kassadin"), listOf("Vi", "Viego", "Nocturne")),
        "taliyah" to Reference(listOf("Syndra", "Zed", "Orianna"), listOf("Jarvan IV", "Vi", "Xin Zhao")),
        "talon" to Reference(listOf("Rengar", "Kindred", "Lee Sin"), listOf("Syndra", "Annie", "Lissandra")),
        "teemo" to Reference(listOf("Ryze", "Rumble", "Wukong"), listOf("Amumu", "Warwick", "Rammus")),
        "thresh" to Reference(listOf("Zyra", "Nami", "Lux"), listOf("Samira", "Jhin", "Draven")),
        "tristana" to Reference(listOf("Kog'Maw", "Caitlyn", "Draven"), listOf("Milio", "Lulu", "Nami")),
        "tryndamere" to Reference(listOf("Rammus", "Maestro Yi", "Amumu"), listOf("Lulu", "Rakan", "Milio")),
        "twisted_fate" to Reference(listOf("Syndra", "Morgana", "Mel"), listOf("Camille", "Shen", "Nocturne")),
        "twitch" to Reference(listOf("Ashe", "Samira", "Caitlyn"), listOf("Lulu", "Yuumi", "Nami")),
        "urgot" to Reference(listOf("Mordekaiser", "Fiora", "Vayne"), listOf("Rammus", "Lissandra", "Veigar")),
        "varus" to Reference(listOf("Smolder", "Miss Fortune", "Vayne"), listOf("Karma", "Lulu", "Milio")),
        "vayne" to Reference(listOf("Caitlyn", "Ashe", "Draven"), listOf("Lulu", "Soraka", "Karma")),
        "veigar" to Reference(listOf("Syndra", "Viktor", "Kassadin"), listOf("Viego", "Vi", "Jarvan IV")),
        "vel_koz" to Reference(listOf("Yone", "Fizz", "Kassadin"), listOf("Jarvan IV", "Amumu", "Leona")),
        "vex" to Reference(listOf("Lissandra", "Galio", "Veigar"), listOf("Amumu", "Viego", "Blitzcrank")),
        "vi" to Reference(listOf("Kindred", "Amumu", "Warwick"), listOf("Annie", "Shen", "Vel'Koz")),
        "viego" to Reference(listOf("Rammus", "Amumu", "Warwick"), listOf("Nautilus", "Leona", "Shen")),
        "viktor" to Reference(listOf("Zed", "Yone", "Kassadin"), listOf("Jarvan IV", "Amumu", "Aatrox")),
        "vladimir" to Reference(listOf("Orianna", "Kassadin", "Viktor"), listOf("Zilean", "Wukong", "Amumu")),
        "volibear" to Reference(listOf("Lillia", "Evelynn", "Kindred"), listOf("Lulu", "Braum", "Ornn")),
        "warwick" to Reference(listOf("Amumu", "Olaf", "Kindred"), listOf("Shen", "Lulu", "Rakan")),
        "wukong" to Reference(listOf("Rammus", "Lillia", "Warwick"), listOf("Yasuo", "Volibear", "Leona")),
        "xayah" to Reference(listOf("Caitlyn", "Vayne", "Kog'Maw"), listOf("Rakan", "Nautilus", "Alistar")),
        "xin_zhao" to Reference(listOf("Rammus", "Shyvana", "Maestro Yi"), listOf("Lulu", "Camille", "Malphite")),
        "yasuo" to Reference(listOf("Teemo", "Vex", "Irelia"), listOf("Malphite", "Rakan", "Gragas")),
        "yone" to Reference(listOf("Ahri", "Vex", "Zed"), listOf("Lillia", "Fiddlesticks", "Nunu y Willump")),
        "yunara" to Reference(listOf("Smolder", "Miss Fortune", "Caitlyn"), listOf("Lulu", "Milio", "Braum")),
        "yuumi" to Reference(listOf("Nautilus", "Thresh", "Alistar"), listOf("Lucian", "Zeri", "Jinx")),
        "zed" to Reference(listOf("Lissandra", "Yasuo", "Vex"), listOf("Shen", "Nautilus", "Amumu")),
        "zeri" to Reference(listOf("Kog'Maw", "Caitlyn", "Lucian"), listOf("Yuumi", "Milio", "Lulu")),
        "ziggs" to Reference(listOf("Yasuo", "Zed", "Yone"), listOf("Amumu", "Leona", "Jarvan IV")),
        "zilean" to Reference(listOf("Maokai", "Rell", "Pyke"), listOf("Jhin", "Vayne", "Ashe")),
        "zoe" to Reference(listOf("Morgana", "Yasuo", "Irelia"), listOf("Jayce", "Jhin", "Viego")),
        "zyra" to Reference(listOf("Karma", "Rakan", "Nami"), listOf("Ezreal", "Caitlyn", "Ashe"))
    )
}

