
package com.example.util

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.Composable
import com.example.data.WildRiftRepository
import androidx.compose.ui.res.stringResource

val LocalLanguage = compositionLocalOf { "es" }

val translations = mapOf(
    "es" to mapOf(
        "PermisoSuperposicionTexto" to "1. Toca en 'Conceder Permiso'.\n2. Habilita el interruptor para Coach.\n3. Vuelve a la aplicación y presiona ACTIVAR.",
        "release_notes_fallback" to "• Optimizaciones de rendimiento en el asistente inteligente.\n• Actualización de sinergias y counters para el parche actual de Wild Rift.\n• Mejoras en la interfaz y navegación rápida.",
        "Temas (13)" to "Temas (13)",
        "Heal" to "Curar",
        "Smite" to "Aplastar",
        "Ignite" to "Prender",
        "Flash" to "Destello",
        "Ghost" to "Fantasmal",
        "Barrier" to "Barrera",
        "Exhaust" to "Extenuación",
        "Cleanse" to "Limpiar",
        "Teleport" to "Teleportar",
        "Clarity" to "Claridad",
        "Mark / Dash" to "Marca y Deslizamiento",
        "Serpent's Fang" to "Colmillo de serpiente",
        "Chempunk Chainsword" to "Espada sierra quimopunk",
        "Sterak's Gage" to "Guantelete de Sterak",
        "Parche 7.2d" to "Parche 7.2d",
    ),
    "pt" to mapOf(
        "Cosecha Oscura" to "Colheita Sombria",
        "Electrocutar" to "Eletrocutar",
        "Compás Letal" to "Ritmo Fatal",
        "Conquistador" to "Conquistador",
        "Aumento Glacial" to "Aprimoramento Glacial",
        "Primer Golpe" to "Primeiro Ataque",
        "Fase Veloz" to "Ímpeto Gradual",
        "Reverberacción" to "Pós-choque",
        "Reverberación" to "Pós-choque",
        "Fuente de Vida" to "Fonte da Vida",
        "Garras del Inmortal" to "Aperto dos Mortos-Vivos",
        "Guardián" to "Guardião",
        "Cometa Arcano" to "Cometa Arcano",
        "Invocar a Aery" to "Invocar Aery",
        "Soberano Gélido" to "Aprimoramento Glacial",
        "Fortalecimiento" to "Fortalecimento",
        "Pies Veloces" to "Agilidade nos Pés",
        "Ataque Intensificado" to "Pressione o Ataque",
        "Impacto Súbito" to "Impacto Repentino",
        "Debilidad" to "Fraqueza",
        "Marca de los Débiles" to "Marca do Fraco",
        "Marca del Débil" to "Marca do Fraco",
        "Golpe Bajo" to "Golpe Desleal",
        "Poro Fantasma" to "Poro Fantasma",
        "Colección de Globos Oculares" to "Globos Oculares",
        "Cazador Ingenioso" to "Caçador Ardil",
        "Coraza Ósea" to "Osso Revestido",
        "Fuerzas Renovadas" to "Ventos Revigorantes",
        "Condicionamiento" to "Condicionamento",
        "Crecimiento Excesivo" to "Crescimento Excessivo",
        "Inquebrantable" to "Inabalável",
        "Revitalizar" to "Revitalizar",
        "Quemadura" to "Chamuscar",
        "Tormenta Creciente" to "Tempestade Crescente",
        "Trascendencia" to "Transcendência",
        "Anillo de Flujo de Maná" to "Faixa de Fluxo de Mana",
        "Capa del Nimbo" to "Manto de Nimbus",
        "Bandolada de Maná" to "Faixa de Fluxo de Mana",
        "Triunfo" to "Triunfo",
        "Claridad Mental" to "Presença de Espírito",
        "Leyenda: Celeridad" to "Lenda: Espontaneidade",
        "Leyenda: Tenacidad" to "Lenda: Tenacidade",
        "Leyenda: Linaje" to "Lenda: Linhagem",
        "Último Esfuerzo" to "Até a Morte",
        "Golpe de Gracia" to "Golpe de Misericórdia",
        "Cazador Cazado" to "Dilacerar",
        "Derribado" to "Dilacerar",
        "Dulces Frutos" to "Fruto Doce",
        "Cazador: Genio" to "Caçador: Gênio",
        "Tropa" to "Caçador em Bando",
        "Destructor" to "Demolir",
        "Mente Maestra" to "Mente Mestra",
        "Cazador - Titán" to "Caçador - Titã",
        "Cazador - Vampirismo" to "Caçador - Vampirismo",
        "Se Avecina Tormenta" to "Tempestade Crescente",
        "Calzado Mágico" to "Calçados Mágicos",
        "Mercado del Futuro" to "Mercado do Futuro",
        "Entrega de Galletas" to "Entrega de Biscoitos",
        "Perspicacia Cósmica" to "Perspicácia Cósmica",
        "Velocidad de Aproximación" to "Velocidade de Aproximação",
        "Tónico de Distorsión Temporal" to "Tônico de Distorção no Tempo",
        "Destello Hextech" to "Flashtração Hextec",
        "Golpe Escudo" to "Golpe de Escudo",
        "Fantasmal" to "Fantasma",
        "Curar" to "Curar",
        "Barrera" to "Barreira",
        "Extenuación" to "Exaustão",
        "Destello" to "Flash",
        "Prender" to "Incendiar",
        "Castigo" to "Golpear",
        "Aplastar" to "Golpear",
        "Estasis" to "Estase",
        "Claridad" to "Clareza",
        "Marca / Lanzamiento" to "Marcação / Avanço",

        "Tema" to "Tema",
        "Temas" to "Temas",
        "Tema:" to "Tema:",
        "Temas:" to "Temas:",
        "Apoyar el Proyecto" to "Apoiar o Projeto",
        "Donaciones" to "Doações",
        "Donaciones y Comunidad" to "Doações e Comunidade",
        "Rendimiento en Segundo Plano" to "Desempenho em Segundo Plano",
        "Para un funcionamiento óptimo, permite la actividad en segundo plano y desactiva el ahorro de batería en esta app." to "Para um funcionamento ideal, permita a atividade em segundo plano e desative a economia de bateria neste app.",
        "Ajustes" to "Ajustes",
        "Descargando Recursos..." to "Baixando Recursos...",
        "Descargando Recursos" to "Baixando Recursos",
        "Descarga Finalizada" to "Download Finalizado",
        " Favorable en carril" to " Favorável na rota",
        "Automático (Sincronizado con Tema)" to "Automático (Sincronizado com Tema)",
        "Hextech Cian" to "Hextech Ciano",
        "Se adapta automáticamente a la paleta activa" to "Adapta-se automaticamente à paleta ativa",
        "Resplandor cian arcano dedicado" to "Brilho ciano arcano dedicado",
        "Iniciando descarga de recursos en segundo plano..." to "Iniciando download de recursos em segundo plano...",
        "Total de elementos:" to "Total de elementos:",
        "recursos" to "recursos",
        "nuevos" to "novos",
        "En caché" to "Em cache",
        "Descargando" to "Baixando",
        "Reintentando" to "Tentando novamente",
        "Descarga completada con éxito." to "Download concluído com sucesso.",
        "Filtrar por Categoría" to "Filtrar por Categoria",
        "Filtrar por Rol" to "Filtrar por Função",
        "Minimizar filtros" to "Minimizar filtros",
        "Expandir filtros" to "Expandir filtros",
        "Entendido / Cerrar" to "Entendido / Fechar",
        "¡Gracias por apoyar a la comunidad!" to "Obrigado por apoiar a comunidade!",
        "Cada aporte cuenta para seguir mejorando el asistente táctico, las builds y la precisión de análisis en tiempo real." to "Cada contribuição conta para continuar melhorando o assistente tático, as builds e a precisão das análises em tempo real.",
        "Coach es una app sin anuncios molestos. Si la app te ayuda a subir de elo y ganar partidas, tu donación permite mantener los servidores y actualizaciones constantes." to "O Coach é um aplicativo sem anúncios irritantes. Se o app te ajuda a subir de elo e vencer partidas, sua doação ajuda a manter os servidores e atualizações constantes.",
        "Métodos de Donación Disponibles:" to "Métodos de Doação Disponíveis:",
        "Donación internacional rápida" to "Doação internacional rápida",
        "Abrir PayPal" to "Abrir PayPal",
        "Invita un café al desarrollador" to "Pague um café para o desenvolvedor",
        "Abrir Ko-fi" to "Abrir Ko-fi",
        "Copiar" to "Copiar",
        "Copiado al portapapeles" to "Copiado para a área de transferência",
        "ACTIVO" to "ATIVO",
        "AUTO" to "AUTO",
        "ELEGIR" to "ESCOLHER",
        "Bueno contra:" to "Bom contra:",
        "Verdadero" to "Verdadeiro",
        "Hechizos Recomendados para esta Línea:" to "Feitiços Recomendados para esta Rota:",
        "Paso 4: Consulta de Builds y Runas" to "Passo 4: Consulta de Builds e Runas",
        "En vivo:" to "Ao vivo:",
        "Seleccionar Mi Campeón" to "Selecionar Meu Campeão",
        "Objetos Situacionales Recomendados:" to "Itens Situacionais Recomendados:",
        "Toca para ver build completa" to "Toque para ver a build completa",
        "CAMBIOS SITUACIONALES" to "MUDANÇAS SITUACIONAIS",
        "Buscar runa (ej. Conquistador, Banda de Flujo)..." to "Buscar runa (ex: Conquistador, Faixa de Fluxo)...",
        "Coach" to "Coach",
        "Configuración de Runas para esta Línea:" to "Configuração de Runas para esta Rota:",
        "Selecciona tu Línea para esta Partida" to "Selecione sua Rota para esta Partida",
        "Táctica:" to "Tática:",
        "Abrir Panel de Administrador (Buzón de Reportes)" to "Abrir Painel de Administrador (Caixa de Relatórios)",
        "Estadísticas, hechizos, runas y build adaptadas a" to "Estatísticas, feitiços, runas e build adaptadas para",
        "Blind Pick" to "Blind Pick",
        "Mi Línea:" to "Minha Rota:",
        "Mejora:" to "Melhoria:",
        "Ordenar:" to "Ordenar por:",
        "Runas Oficiales" to "Runas Oficiais",
        " Buena elección para tu línea" to " Boa escolha para sua rota",
        " Runas:" to " Runas:",
        "Alerta Táctica de Matchup" to "Alerta Tático de Matchup",
        "Build Completa (6 Objetos):" to "Build Completa (6 Itens):",
        "️ Considera cambiarlo" to "️ Considere trocar",
        "Balance de Daño Rival" to "Balanço de Dano Inimigo",
        "Balance de Daño Aliado" to "Balanço de Dano Aliado",
        "Exceso de Daño Físico aliado (AD)." to "Excesso de Dano Físico aliado (AD).",
        "Exceso de Daño Mágico aliado (AP)." to "Excesso de Dano Mágico aliado (AP).",
        "Buscar hechizo (ej. Destello, Prender, Castigo)..." to "Buscar feitiço (ex: Flash, Incendiar, Golpear)...",
        "Revisa los consejos tácticos, orden de habilidades móviles (Pasiva, 1, 2, 3, Definitiva) y armado de objetos recomendado para tu línea." to "Revise as dicas táticas, ordem de habilidades (Passiva, 1, 2, 3, Ultimate) e itens recomendados para sua rota.",
        "Clasificación por" to "Classificação por",
        "Counter" to "Counter",
        "WR" to "WR",
        "Caché:" to "Cache:",

        "Línea:" to "Rota:",
        "1er Pick" to "1º Pick",
        "1ª Elección Segura" to "1º Pick (Seguro)",
        "Inicio" to "Início",
        "Catálogo" to "Catálogo",
        "Top" to "Topo",
        "Mid" to "Meio",
        "Jungla" to "Selva",
        "Dúo" to "Duo",
        "Soporte" to "Suporte",
        "Flex en " to "Flex em ",
        "Principal: " to "Principal: ",
        "Flex: " to "Flex: ",
        "Draft" to "Draft",
        "CDs" to "CDs",
        "Daño" to "Dano",
        "Obj" to "Obj",
        "Build" to "Build",
        "Detener Asistente" to "Parar Assistente",
        "Minimizar HUD" to "Minimizar HUD",
        "MEJOR OPCIÓN ABSOLUTA" to "MELHOR OPÇÃO ABSOLUTA",
        "Fijar" to "Fixar",
        "y Ver Runas / Build" to "e Ver Runas / Build",
        "Otras Alternativas en " to "Outras Alternativas em ",
        "Selecciona un campeón para ver su página de runas óptima" to "Selecione um campeão para ver sua página de runas ideal",
        "Fijado" to "Fixado",
        "Página de Runas" to "Página de Runas",
        "Runa Clave Recomendada" to "Runa Essencial Recomendada",
        "Selecciona un campeón para ver sus hechizos de invocador recomendados" to "Selecione um campeão para ver seus feitiços de invocador recomendados",
        "Hechizos & Orden de Habilidades" to "Feitiços e Ordem de Habilidades",
        "Hechizos de Invocador Recomendados" to "Feitiços de Invocador Recomendados",
        "Prioridad de Habilidades" to "Prioridade de Habilidades (Ordem de Evolução)",
        "Maxeo:" to "Maximizar:",
        "Hechizos" to "Feitiços",
        "Runas" to "Runas",
        "Destello" to "Flash",
        "Prender" to "Incendiar (Ignite)",
        "Extenuación" to "Exaustão",
        "Barrera" to "Barreira",
        "Curar" to "Curar",
        "Fantasma" to "Fantasma",
        "Estasis" to "Estase (Zhonya)",
        "Definitiva" to "Ultimate",
        "CD Tracker:" to "CD Tracker:",
        "Rival" to "Inimigo",
        "Enfriamiento:" to "Tempo de Recarga:",
        "restante" to "restante",
        "Base:" to "Base:",
        "¡Listo para usar!" to "Pronto para usar!",
        "Gastado" to "Gasto",
        "Reiniciar Todos" to "Reiniciar Todos",
        "Envía fallos o sugerencias. Se guardarán directamente en la base de datos (con retención automática de 7 días):" to "Envie falhas ou sugestões. Elas serão salvas diretamente no banco de dados (com retenção automática de 7 dias):",
        "Enviar a Base de Datos" to "Enviar para o Banco de Dados",
        "Enviando a Base de Datos..." to "Enviando para o Banco de Dados...",
        "Limpiar Reportes Antiguos (> 7 días)" to "Limpar Relatórios Antigos (> 7 dias)",
        "Módulo de sincronización de la base de datos en la nube. Pulsa el botón para probar la conexión o gestionar la retención de reportes." to "Módulo de sincronização do banco de dados na nuvem. Pressione o botão para testar a conexão ou gerenciar a retenção de relatórios.",

        "Estado del Servidor" to "Status do Servidor",
        "Módulo de sincronización de la base de datos en la nube. Pulsa el botón para probar la conexión." to "Módulo de sincronização do banco de dados na nuvem. Pressione o botão para testar a conexão.",
        "Conectando con el servidor..." to "Conectando ao servidor...",
        " Conexión exitosa. Cliente inicializado." to " Conexão bem-sucedida. Cliente inicializado.",
        " Error de conexión: " to " Erro de conexão: ",
        "Verificar Conexión del Servidor" to "Verificar Conexão do Servidor",


        // Draft UI Extra
        "Equipo Aliado" to "Equipe Aliada",
        "Equipo Rival" to "Equipe Inimiga",
        "Seleccionar Campeón Aliado" to "Selecionar Campeão Aliado",
        "Seleccionar Campeón Rival" to "Selecionar Campeão Inimigo",

        // Modal de Bienvenida del Parche
        "¡Bienvenidos a Coach!" to "Bem-vindos ao Coach!",
        "Estado del Parche: " to "Status do Patch: ",
        "Estado del Parche:" to "Status do Patch:",
        "Versión del Parche:" to "Versão do Patch:",
        "Versión del Parche de Wild Rift:" to "Versão do Patch do Wild Rift:",
        "Parche" to "Patch",
        "parche" to "patch",
        "Parches" to "Patches",
        "parches" to "patches",
        "Parche 7.2d" to "Patch 7.2d",
        "Parche 7.2c" to "Patch 7.2c",
        "Parche 7.2b" to "Patch 7.2b",
        "Parche 7.2a" to "Patch 7.2a",
        "Parche 7.2" to "Patch 7.2",
        "1. Compatibilidad y Parche Oficial" to "1. Compatibilidade e Patch Oficial",
        "Ver Notas de Bienvenida y Novedades del Parche" to "Novidades",
        "Novedades" to "Novidades",
        "Runas en Español, Parches y Novedades" to "Runas, Patches e Novidades",
        "Catálogo Completo de Objetos" to "Catálogo Completo de Itens",
        "Sincronizado con wr-meta.com con descripciones, estadísticas y costes actualizados." to "Sincronizado com wr-meta.com com descrições, estatísticas e custos atualizados.",
        "Overlay Flotante Táctico" to "Overlay Flutuante Tático",
        "Asistente en tiempo real durante tu fase de selección y partida en Wild Rift." to "Assistente em tempo real durante a fase de seleção e partida no Wild Rift.",
        "Seguridad y Rendimiento" to "Segurança e Desempenho",
        "Ícono adaptativo optimizado para todas las capas de personalización (Xiaomi/Samsung)." to "Ícone adaptativo otimizado para todas as camadas de personalização (Xiaomi/Samsung).",
        "¡Comenzar / Entendido!" to "Começar / Entendido!",
        "Coach v2.11" to "Coach v2.11",
        "Renombre oficial, contadores dinámicos en catálogos y evaluación táctica de tu pick en tiempo real." to "Renomeação oficial, contadores dinâmicos nos catálogos e avaliação tática do seu pick em tempo real.",
        "Coach v2.0" to "Coach v2.0",
        "Lanzamiento del asistente táctico flotante, catálogo de objetos completo y soporte multi-idioma." to "Lançamento do assistente tático flutuante, catálogo de itens completo e suporte multi-idioma.",
        "Sincronización Oficial" to "Sincronização Oficial",
        "Base de datos de campeones actualizada al parche del juego: " to "Banco de dados de campeões atualizado para o patch do jogo: ",
        "Nuevos ítems de luchador, balances en jungla y adición de evaluación en tiempo real de tu propio campeón durante el draft." to "Novos itens de lutador, balanceamentos na selva e adição de avaliação em tempo real do seu próprio campeão durante o draft.",
        "Ajustes de daño en campeones ADC y mejoras de estabilidad en el catálogo de runas." to "Ajustes de dano em campeões ADC e melhorias de estabilidade no catálogo de runas.",
        "Sincronización oficial del metajuego, estadísticas base y nuevos encantamientos." to "Sincronização oficial do metajogo, estatísticas base e novos encantamentos.",
        "Gran parche de temporada: Rediseño completo de la grieta y adición del asistente overlay flotante." to "Grande patch de temporada: Redesenho completo do mapa e adição do assistente overlay flutuante.",
        "Actual" to "Atual",
        "Cerrar" to "Fechar",

        "¡Bienvenidos!" to "Bem-vindos!",
        "Notas del Nuevo Parche" to "Notas do Novo Patch",
        "• Sincronización automática con: " to "• Sincronização automática com: ",
        "• Análisis táctico actualizado con las últimas estadísticas del meta.\n" to "• Análise tática atualizada com as últimas estatísticas do meta.\n",
        "• Ajustes y corrección de íconos rúnicos." to "• Ajustes e correção de ícones rúnicos.",
        "Organización: Coach de Élite" to "Organização: Coach de Elite (Coach)",
        "Entendido" to "Entendido",
        "El rival tiene alta iniciación de CC con Sett y Vi. Se aconseja desengage, escudos antimagia o tenacidad." to "O inimigo tem alta iniciação de CC com Sett e Vi. É aconselhável desengage, escudos antimagia ou tenacidade.",
        "Caitlyn rival tiene ventaja de rango en carril de Dragón. Prioriza anulación con Viego o agarre con Nautilus/Blitzcrank." to "Caitlyn inimiga tem vantagem de alcance na Rota do Dragão. Priorize anulação com Viego ou puxão com Nautilus/Blitzcrank.",
        "Peligro de asesinos de burst" to "Perigo de assassinos de burst",
        "Imprescindible Zhonya/Estasis y CC garantizado (Lulu, Malzahar, Nautilus)." to "Imprescindível Zhonya/Estase e CC garantido (Lulu, Malzahar, Nautilus).",
        "Composición rival pesada" to "Composição inimiga pesada",
        "Requiere daño verdadero y % vida máxima." to "Requer dano verdadeiro e % de vida máxima.",
        "Morgana o Janna" to "Morgana ou Janna",
        "Nautilus o Viego" to "Nautilus ou Viego",
        "Lulu, Nautilus o Zhonya" to "Lulu, Nautilus ou Zhonya",
        "Vayne, Sett, Gwen o Liandry" to "Vayne, Sett, Gwen ou Liandry",
        "Conquistador (Precisión)" to "Conquistador (Precisão)",
        "Táctico" to "Tático",
        "Daño Físico" to "Dano Físico",
        "Daño Mágico" to "Dano Mágico",
        "Daño Verdadero" to "Dano Verdadeiro",
        "Tanque" to "Tanque",
        "Mago" to "Mago",
        "Luchador" to "Lutador",
        "Asesino" to "Assassino",
        "Tirador" to "Atirador",
        "Soporte" to "Suporte",
        "Top" to "Topo",
        "Jungla" to "Caçador",
        "Medio" to "Meio",
        "Dúo" to "Atirador",
        "Línea de Barón" to "Rota do Barão",
        "Línea de Medio" to "Rota do Meio",
        "Línea de Dragón" to "Rota do Dragão",
        " Si tu dispositivo muestra 'conflicto con un paquete', desinstala la versión anterior de tu teléfono una sola vez e instala la nueva APK (ocurre por cambio de firma de depurado a producción)." to " Se o seu dispositivo mostrar 'conflito de pacote', desinstale a versão anterior do seu telefone uma vez e instale o novo APK (ocorre devido à alteração da assinatura de depuração para produção)."
,
        "Acerca De" to "Sobre",
        "5. Desarrollador y Derechos de Autor" to "5. Desenvolvedor e Direitos Autorais",
        "Aplicación creada y desarrollada por Diego Barba Chavez." to "Aplicativo criado e desenvolvido por Diego Barba Chavez.",
        "Todos los derechos reservados." to "Todos os direitos reservados.",
        "Creador & Desarrollador Principal • Todos los derechos reservados" to "Criador & Desenvolvedor Principal • Todos os direitos reservados",
        "Diseñado para la comunidad competitiva de League of Legends: Wild Rift." to "Projetado para a comunidade competitiva de League of Legends: Wild Rift.",
        "Asistente Táctico Wild Rift" to "Assistente Tático Wild Rift",
        "Guía en Tiempo Real para Selección de Campeones" to "Guia em Tempo Real para Seleção de Campeões",
        "1. Acerca del Asistente" to "1. Sobre o Assistente",
        "Edición Móvil" to "Edição Móvel",
        "• Compatibilidad: Diseñado exclusivamente para Wild Rift (habilidades móviles, runas de Wild Rift, balance y objetos móviles)." to "• Compatibilidade: Projetado exclusivamente para o Wild Rift (habilidades móveis, runas do Wild Rift, balanceamento e itens móveis).",
        "• Parche del juego: " to "• Patch do jogo: ",
        "sincronizado con fuentes de balance." to "sincronizado com fontes de balanceamento.",
        "• Motor Hextech: Botón de activación directa con cálculo de composiciones, counters y sinergias." to "• Motor Hextech: Botão de ativação direta com cálculo de composições, counters e sinergias.",
        "• Sistema Flotante: Ventana superpuesta en pantalla con controles táctiles para la fase de selección." to "• Sistema Flutuante: Janela sobreposta na tela com controles sensíveis ao toque para a fase de seleção.",
        "2. Modo de Uso de la Aplicación" to "2. Modo de Uso do Aplicativo",
        "Paso 1: Configura tus Líneas de Juego" to "Passo 1: Configure suas Rotas de Jogo",
        "En la pantalla principal, selecciona tu 'Línea Main', 'Segunda Línea' y 'Rol Autofill' tocando cada tarjeta." to "Na tela principal, selecione sua 'Rota Principal', 'Segunda Rota' e 'Função de Preenchimento Automático' tocando em cada cartão.",
        "Paso 2: Activa el Asistente Flotante" to "Passo 2: Ative o Assistente Flutuante",
        "Pulsa el botón central 'ACTIVAR'. Se desplegará la burbuja flotante en pantalla para acompañarte en tu partida." to "Pressione o botão central 'ATIVAR'. A bolha flutuante será exibida na tela para acompanhá-lo em sua partida.",
        "Paso 3: Selección de Campeones" to "Passo 3: Seleção de Campeões (Champ Select)",
        "Abre Wild Rift y entra a la fase de selección. Toca el botón flotante en cualquier momento para ver recomendaciones, counters y sinergias tácticas en directo." to "Abra o Wild Rift e entre na fase de seleção. Toque no botão flutuante a qualquer momento para ver recomendações, counters e sinergias táticas ao vivo.",
        "Paso 4: Filtros Automáticos" to "Passo 4: Filtros Automáticos",
        "El asistente prioriza campeones según los roles que hayas configurado en el Paso 1, permitiendo una selección más rápida antes de que se acabe el tiempo." to "O assistente prioriza campeões de acordo com as funções que você configurou no Passo 1, permitindo uma seleção mais rápida antes que o tempo acabe.",
        "3. Interfaz del Asistente" to "3. Interface do Assistente (Overlay HUD)",
        "Pestaña Draft" to "Guia Draft (Ícone Lista)",
        "Recomendaciones de picks seguros, counter picks directos y sinergias basándose en tu rol." to "Recomendações de picks seguros, counter picks diretos e sinergias baseadas na sua função.",
        "Pestaña Objetivos" to "Guia Objetivos (Ícone Mapa)",
        "Tiempos de reaparición (spawn) de los monstruos neutrales épicos." to "Tempos de reaparecimento (spawn) dos monstros neutros épicos.",
        "Pestaña Objetos" to "Guia Itens (Ícone Espada)",
        "Builds sugeridas para el campeón seleccionado (Core items y situacionales)." to "Builds sugeridas para o campeão selecionado (Core items e situacionais).",
        "Pestaña Runas" to "Guia Runas (Ícone Magia)",
        "Página de runas meta óptimas para el campeón sugerido." to "Página de runas meta ideais para o campeão sugerido.",
        "Deslizar para Minimizar" to "Deslizar para Minimizar",
        "Puedes deslizar el panel hacia abajo en cualquier momento para ocultarlo temporalmente sin detener la herramienta." to "Você pode deslizar o painel para baixo a qualquer momento para ocultá-lo temporariamente sem interromper a ferramenta.",
        "Versión del Parche de Wild Rift:" to "Versão do Patch do Wild Rift:",
        "Build y Runas de" to "Build e Runas de",
        "Básicos" to "Básicos",
        "Nivel Medio" to "Nível Médio",
        "Botas N2" to "Botas N2",
        "Botas N3" to "Botas N3",
        "Encantamientos" to "Encantamentos",
        "ÍTEMS BÁSICOS" to "ITENS BÁSICOS (BASIC ITEMS)",
        "ÍTEMS DE NIVEL MEDIO" to "ITENS DE NÍVEL MÉDIO (MID TIER)",
        "DAÑO FÍSICO" to "DANO FÍSICO (PHYSICAL DAMAGE)",
        "DAÑO MÁGICO" to "DANO MÁGICO (MAGIC DAMAGE)",
        "DEFENSA" to "DEFESA (DEFENSIVE ITEMS)",
        "SOPORTE" to "SUPORTE (SUPPORT ITEMS)",
        "BOTAS NIVEL 2" to "BOTAS NÍVEL 2 (BOOTS TIER 2)",
        "BOTAS NIVEL 3" to "BOTAS NÍVEL 3 (BOOTS TIER 3)",
        "ENCANTAMIENTOS Y ACTIVOS" to "ENCANTAMENTOS E ATIVOS (ACTIVE ITEMS)",
        "Cuadrícula" to "Grade",
        "Detallado" to "Detalhado",
        "Buscar objeto por nombre o estadísticas..." to "Buscar item por nome ou atributos...",
        "Estadísticas:" to "Atributos:",
        "Efecto / Pasiva:" to "Efeito / Passiva:",
        "Coste:" to "Custo:",
        "Oro" to "Ouro",

        "Elige tu idioma" to "Escolha seu idioma",
        "Español" to "Espanhol",
        "Inglés" to "Inglês",
        "Portugués" to "Português",
        "Continuar" to "Continuar",
        "Información Legal" to "Informações Legais",
        "Debes aceptar los Términos de Servicio y la Política de Privacidad para poder ingresar a la aplicación. Si cierras esta ventana, la aplicación se cerrará." to "Você deve aceitar os Termos de Serviço e a Política de Privacidade para poder entrar no aplicativo. Se fechar esta janela, o aplicativo será encerrado.",
        "Rechazar y Salir" to "Recusar e Sair",
        "Aceptar y Entrar" to "Aceitar e Entrar",
        "Cerrar y Salir" to "Fechar e Sair",
        "Permiso de Superposición" to "Permissão de Sobreposição",
        "Para que el asistente inteligente funcione en segundo plano sobre Wild Rift, Android requiere habilitar 'Aparecer encima' (Superposición)." to "Para que o assistente inteligente funcione em segundo plano sobre o Wild Rift, o Android requer a ativação da permissão 'Aparecer sobre outros apps'.",
        "El asistente proporciona lecturas de pantalla y sugerencias en tiempo real sin salir del juego." to "O assistente fornece leituras de tela e sugestões em tempo real sem sair do jogo.",
        "Conceder Permiso" to "Conceder Permissão",
        "Cancelar" to "Cancelar",
        "Base de Datos Tier List (Parche 16.16.1)" to "Banco de Dados Tier List (Patch 16.16.1)",
        "Campeones" to "Campeões",
        "Sinergias" to "Sinergias",
        "Items" to "Itens",
        "Runas" to "Runas",
        "Hechizos de Invocador:" to "Feitiços de Invocador:",
        "Árbol de Runas:" to "Árvore de Runas:",
        "Objetos Básicos:" to "Itens Principais (Core):",
        "Objetos Situacionales:" to "Itens Situacionais:",
        "Mejores Sinergias:" to "Melhores Sinergias (Composição):",
        "Ventaja Contra:" to "Forte Contra:",
        "Débil Contra:" to "Fraco Contra:",
        "Entendido" to "Entendido",
        "Analizando Draft..." to "Analisando Draft...",
        "Activar Asistente" to "Ativar Assistente (Sobreposição)",
        "Buscando composiciones óptimas y counters..." to "Buscando composições ideais e counters...",
        "Asistente Wild Rift" to "Assistente Wild Rift",
        "Cerrar" to "Fechar",
        "Error" to "Erro",
        "Información" to "Informação",
        "MID" to "MID",
        "TOP" to "TOP",
        "JUNGLE" to "JUNGLE",
        "ADC" to "ADC",
        "SUPPORT" to "SUPPORT",
        "Daño" to "Dano",
        "Roles" to "Funções",
        "Buscando composiciones..." to "Buscando composições...",
        "PermisoSuperposicionTexto" to "1. Toque em 'Conceder Permissão'.\n2. Ative o interruptor para o Coach.\n3. Volte ao aplicativo e pressione ATIVAR.",
        "Línea Main" to "Rota Principal",
        "Segunda Línea" to "Segunda Rota",
        "Rol Autofill" to "Função Preenchimento Automático",
        "Tier List & Catálogo de Campeones" to "Tier List & Catálogo de Campeões",
        "Tier list, counters, sinergias, runas y objetos" to "Tier list, counters, sinergias, runas e itens",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Assistente Hextech Ativo • Toque na câmera flutuante",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Pressione ATIVAR para iniciar o Assistente Flutuante",
        " Mejor Primer Pick Seguro para" to " Melhor Primeiro Pick Seguro para",
        " Mejor Opción según tu Equipo y el Rival" to " Melhor Opção segundo sua Equipe e o Rival",
        " #1 RECOMENDACIÓN BLIND PICK" to " #1 RECOMENDAÇÃO BLIND PICK",
        " #1 MEJOR ELECCIÓN TÁCTICA" to " #1 MELHOR ESCOLHA TÁTICA",
        "Winrate Est.:" to "Taxa de Vitória Est.:",
        " Runas recomendadas:" to " Runas recomendadas:",
        "Toca para ver build" to "Toque para ver a build",
        "Otras Opciones Viables para" to "Outras Opções Viáveis para",
        "Alerta de Composición Rival" to "Alerta de Composição Inimiga",
        "Añadir" to "Adicionar",
        "Eliminar" to "Remover",
        "ACTIVAR" to "ATIVAR",
        "DETENER" to "PARAR",
        "Volver" to "Voltar",
        "Reiniciar Draft" to "Reiniciar Draft",
        "Drafting" to "Drafting",
        "Selección" to "Seleção",
        "Selección de Campeones" to "Seleção de Campeões",
        "Tier List & Campeones" to "Tier List & Campeões",
        "Campeones" to "Campeões",
        "Tier List" to "Tier List",
        "Objetos" to "Itens",
        "Ítems" to "Itens",
        "Ítem" to "Item",
        "Runas" to "Runas",
        "Hechizos" to "Feitiços",
        "Runas & Hechizos" to "Runas & Feitiços",
        "Objetivos" to "Objetivos",
        "Buscar runa..." to "Buscar runa...",
        "Buscar hechizo..." to "Buscar feitiço...",
        "Runas Wild Rift" to "Runas do Wild Rift",
        "Hechizos de Invocador" to "Feitiços de Invocador",
        "Runas Clave" to "Runas Chave",
        "Dominación" to "Dominação",
        "Precisión" to "Precisão",
        "Valor" to "Determinação",
        "Inspiración" to "Inspiração",
        "Brujería" to "Feitiçaria",
        "Combate & Daño" to "Combate e Dano",
        "Movilidad & Utilidad" to "Mobilidade e Utilidade",
        "Build de" to "Build de",
        "Runas de" to "Runas de",
        "Hechizos de" to "Feitiços de",
        "Habilidades" to "Habilidades",
        "Cambiar" to "Mudar",

        // Líneas & Roles
        "Línea de Barón" to "Rota do Barão",
        "Jungla" to "Selva",
        "Línea Central" to "Rota do Meio",
        "Línea de Dragón" to "Rota do Dragão",
        "Soporte" to "Suporte",
        "Barón" to "Barão",
        "Central" to "Meio",
        "Dragón" to "Dragão",
        "Físico" to "Físico",
        "Mágico" to "Mágico",
        "Híbrido / Verdadero" to "Híbrido / Verdadeiro",
        "Daño Físico" to "Dano Físico",
        "Poder Mágico" to "Poder Mágico",
        "Defensa" to "Defesa",
        "Utilidad" to "Utilidade",
        "Botas" to "Botas",
        "Encantamiento" to "Encantamento",
        "Botas & Encantamientos" to "Botas & Encantamentos",

        // Hechizos de Invocador
        "Destello" to "Flash",
        "Prender" to "Incendiar",
        "Castigo" to "Golpear",
        "Barrera" to "Barreira",
        "Extenuación" to "Exaustão",
        "Fantasma" to "Fantasma",
        "Curar" to "Curar",
        "Claridad" to "Clareza",
        "Marca / Lanzamiento" to "Marcação / Avanço",

        // Runas
        "Conquistador" to "Conquistador",
        "Verdugo de Krakens" to "Mata-Crácens",
        "Cadencia Letal" to "Ritmo Fatal",
        "Electrocutar" to "Eletrocutar",
        "Primer Golpe" to "Primeiro Ataque",
        "Irrupción de Fase" to "Ímpeto Gradual",
        "Agarre del Perpetuo" to "Aperto dos Mortos-Vivos",
        "Réplica" to "Pós-choque",
        "Invocar a Aery" to "Invocar Aery",
        "Aumento Glacial" to "Aprimoramento Glacial",
        "Cometa Arcano" to "Cometa Arcano",
        "Impacto Repentino" to "Impacto Repentino",
        "Quemadura" to "Chamuscar",
        "Colección de Globos Oculares" to "Globos Oculares",
        "Colección de Ojos" to "Globos Oculares",
        "Guardián Zombi" to "Sentinela Zumbi",
        "Centinela Zombi" to "Sentinela Zumbi",
        "Triunfo" to "Triunfo",
        "Brutal" to "Brutal",
        "Fervor de Batalla" to "Fervor da Batalha",
        "Derribado" to "Dilacerar",
        "Golpe de Gracia" to "Golpe de Misericórdia",
        "Último Esfuerzo" to "Até a Morte",
        "Leyenda: Presteza" to "Lenda: Espontaneidade",
        "Leyenda: Celeridad" to "Lenda: Espontaneidade",
        "Leyenda: Tenacidad" to "Lenda: Tenacidade",
        "Leyenda: Linaje" to "Lenda: Linhagem",
        "Golpe Bajo" to "Golpe Desleal",
        "Impacto Repentino" to "Impacto Repentino",
        "Ataque Potenciado" to "Ataque Fortalecido",
        "Asalto Encadenado" to "Assalto Encadeado",
        "Tirano" to "Tirano",
        "Soberbia" to "Arrogância",
        "Cazador Ingenioso" to "Caçador Engenhoso",
        "Cazador Incesante" to "Caçador Incansável",
        "Revestimiento de Huesos" to "Osso Revestido",
        "Fuerzas Renovadas" to "Ventos Revigorantes",
        "Orbe Anulador" to "Orbe Anulador",
        "Coraje del Coloso" to "Coragem do Colosso",
        "Inquebrantable" to "Inabalável",
        "Sobrecrecimiento" to "Crescimento Excessivo",
        "Fuente de Vida" to "Fonte da Vida",
        "Demoler" to "Demolir",
        "Dulces Frutos" to "Fruto Mel",
        "Banda de Flujo de Maná" to "Faixa de Fluxo de Mana",
        "Banda de Maná" to "Faixa de Fluxo de Mana",
        "Arcanólogo Axiomático" to "Arcanólogo Axiomático",
        "Trascendencia" to "Transcendência",
        "Celeridad" to "Celeridade",
        "Concentración Absoluta" to "Foco Absoluto",
        "Capa del Nimbo" to "Manto de Nimbus",
        "Piroláser" to "Chamuscar",
        "Se Avecina Tormenta" to "Tempestade Crescente",
        "Botanista" to "Botanista",
        "Hextello" to "Flashtração Hextec",
        "Semillero Ixtalí" to "Sementeira de Ixtal",

        "Runa Clave" to "Runa Essencial",
        "Clave" to "Runa Essencial",
        "Secundaria" to "Secundária",
        "OTRAS RUNAS" to "OUTRAS RUNAS",
        "Dominación" to "Dominação",
        "Precisión" to "Precisão",
        "Valor" to "Determinação",
        "Inspiración" to "Inspiração",
        "Brujería" to "Feitiçaria",
        "Todos" to "Todos",
        "Hechizos" to "Feitiços",
        "Runas Clave" to "Runas Essenciais",

        "Cambiar Rol / Flex Activo:" to "Mudar Função / Flex Ativo:",
        "Toca para alternar" to "Toque para alternar",
        "Análisis Táctico en Wild Rift" to "Análise Tática no Wild Rift",
        "Habilidades de" to "Habilidades de",
        "Pasiva:" to "Passiva:",
        "Habilidad" to "Habilidade",
        "Definitiva:" to "Ultimate:",
        "¡Nueva Versión Disponible!" to "Nova Versão Disponível!",
        "Novedades de la actualización:" to "Novidades da atualização:",
        "Descargar e Instalar" to "Baixar e Instalar",
        "Recordarme más tarde" to "Lembrar mais tarde",
        "Actualizaciones de la Aplicación" to "Atualizações do Aplicativo",
        "Buscar Actualizaciones" to "Verificar Atualizações",
        "Comprobando versión..." to "Verificando versão...",
        "¡Tienes la versión más reciente!" to "Você já está na versão mais recente!",
        "Actualizado:" to "Atualizado:",
        "Sin conexión • Última estadística:" to "Sem conexão • Última estatística:",
        "Auto-Sync 24/7" to "Auto-Sync 24/7",
        "Caché Local" to "Cache Local",
        "Actualizar" to "Atualizar",
        "SOLO" to "TOP",
        "TOP" to "TOP",
        "Top" to "Top",
        "Barón" to "Barão",
        "BARÓN" to "BARÃO",
        "JUNGLA" to "SELVA",
        "Jungla" to "Selva",
        "CENTRAL" to "MEIO",
        "MID" to "MID",
        "Mid" to "Mid",
        "DÚO" to "DUO",
        "Dúo" to "Duo",
        "ADC" to "ADC",
        "SOPORTE" to "SUPORTE",
        "Soporte" to "Suporte",
        "Todos los Roles" to "Todas as Funções",
        "Todas las Líneas" to "Todas as Rotas",
        "Buscar campeón por nombre o habilidad..." to "Buscar campeão por nome ou habilidade...",
        "Buscar objeto por nombre o estadísticas..." to "Buscar item por nome ou atributos...",
        "Buscar campeón fijado..." to "Buscar campeão fixado...",
        "Buscar campeón..." to "Buscar campeão...",
        "Buscar objeto situacional (ej. Heridas, Zhonya)..." to "Buscar item situacional (ex. Corta-cura, Zhonya)...",
        "Monstruos Épicos & Tiempos de Aparición" to "Monstros Épicos e Tempos de Renascimento",
        "Conocer los tiempos exactos de aparición en Wild Rift asegura la victoria de tu equipo:" to "Conhecer os tempos exatos no Wild Rift garante a vitória da sua equipe:",
        "Escanear" to "Escanear",
        "Coste" to "Custo",
        "Oro" to "Ouro",
        "Reaparición" to "Renascimento",
        "Reaparición:" to "Renascimento:",
        " Toca para ver info" to " Toque para ver detalhes",
        "Selecciona un campeón para ver su página de runas óptima" to "Selecione um campeão para ver a página de runas ideal",
        "Selecciona un campeón para ver sus hechizos de invocador recomendados" to "Selecione um campeão para ver os feitiços recomendados",
        "Daño Físico" to "Dano Físico",
        "Daño Mágico" to "Dano Mágico",
        "Poder Mágico" to "Poder Mágico",
        "Defensa" to "Defesa",
        "Soporte" to "Suporte",
        "Objetos Activos" to "Itens Ativos",
        "Botas Nivel 2" to "Botas Nível 2",
        "Botas Nivel 3" to "Botas Nível 3",
        "Nivel Medio" to "Nível Médio",
        "Nivel Básico" to "Nível Básico",
        "Artículos de Nivel Medio" to "Itens de Nível Médio",
        "ARTÍCULOS DE NIVEL MEDIO" to "ITENS DE NÍVEL MÉDIO",
        "Objetos de Nivel Medio" to "Itens de Nível Médio",
        "OBJETOS DE NIVEL MEDIO" to "ITENS DE NÍVEL MÉDIO",
        "Artículos Básicos" to "Itens Básicos",
        "ARTÍCULOS BÁSICOS" to "ITENS BÁSICOS",
        "Objetos con Daños Físicos" to "Itens de Dano Físico",
        "OBJETOS CON DAÑOS FÍSICOS" to "ITENS DE DANO FÍSICO",
        "Objetos de Daño Mágico" to "Itens de Dano Mágico",
        "OBJETOS DE DAÑO MÁGICO" to "ITENS DE DANO MÁGICO",
        "Artículos de Defensa" to "Itens de Defesa",
        "ARTÍCULOS DE DEFENSA" to "ITENS DE DEFESA",
        "Artículos de Apoyo" to "Itens de Suporte",
        "ARTÍCULOS DE APOYO" to "ITENS DE SUPORTE",
        "Objetos de Hechizo Activos" to "Itens de Feitiço Ativos",
        "OBJETOS DE HECHIZO ACTIVOS" to "ITENS DE FEITIÇO ATIVOS",
        "Colgante del profeta" to "Pingente do Profeta",
        "Brazal de cristal" to "Braçadeira de Cristal",
        "Espejo de cristal de Bandle" to "Espelho de Vidro de Bandle",
        "Botas & Encantamientos" to "Botas e Encantamentos",
        "Físico" to "Físico",
        "Mágico" to "Mágico",
        "Híbrido / Verdadero" to "Híbrido / Verdadeiro",
        "Principal:" to "Principal:",
        "Flex:" to "Flex:",
        "Objetos Clave (Build Recomendada)" to "Itens Principais (Build Recomendada)",
        "Objetos Básicos:" to "Itens Principais (Obrigatórios):",
        "Objetos Situacionales:" to "Itens Situacionais:",
        "¿Por qué comprar este objeto?" to "Por que comprar este item?",
        "Efectivo contra:" to "Eficaz contra:",
        "Efecto clave:" to "Efeito chave:",
        "Consejo de compra:" to "Dica de compra:",
        "Tasa de Victoria" to "Taxa de Vitória",
        "Tasa de Selección" to "Taxa de Escolha",
        "Tasa de Bloqueo" to "Taxa de Banimento",
        "Win Rate" to "Taxa de Vitória",
        "Pick Rate" to "Taxa de Escolha",
        "Ban Rate" to "Taxa de Banimento",
        "Hechizos de Invocador" to "Feitiços de Invocador",
        "Runas" to "Runas",
        "Árbol de Runas" to "Árvore de Runas",
        "Cambiar Línea / Rol Activo:" to "Mudar Rota / Função Ativa:",
        "Línea de Barón" to "Rota do Barão",
        "Línea Central" to "Rota do Meio",
        "Línea de Dragón" to "Rota do Dragão",

        // Reportes & Sugerencias
        "Reportes & Sugerencias" to "Relatórios e Sugestões",
        "Reporta fallos o envía sugerencias para mejorar el asistente:" to "Relate bugs ou envie sugestões para melhorar o assistente:",
        "Reportar Bug" to "Reportar Bug",
        "Bug / Error" to "Bug / Erro",
        "Sugerencia" to "Sugestão",
        "Idea / Mejora" to "Ideia / Melhoria",
        "Campeón/Tier List" to "Campeão/Tier List",
        "Tier List / Campeón" to "Tier List / Campeão",
        "Título del reporte o sugerencia" to "Título do relatório ou sugestão",
        "Descripción detallada" to "Descrição detalhada",
        "Ej: El overlay no detecta la pantalla" to "Ex: Overlay não detecta a tela",
        "Ej: Agregar temporizador de dragones con audio" to "Ex: Adicionar cronômetro de dragões com áudio",
        "Ej: Actualizar build recomendada de Veigar" to "Ex: Atualizar build recomendada do Veigar",
        "Describe qué sucedió, cómo reproducirlo o tu idea para mejorar la app..." to "Descreva o que aconteceu, como reproduzir ou sua ideia para melhorar o app...",
        " Diagnóstico:" to " Diagnóstico:",
        "Publicar en GitHub" to "Publicar no GitHub",
        "Copiar" to "Copiar",
        "Copiado" to "Copiado",
        "Abriendo GitHub Issues..." to "Abrindo GitHub Issues...",
        "Reporte copiado al portapapeles " to "Relatório copiado para a área de transferência ",
        "Por favor completa el título y la descripción para publicar." to "Por favor, preencha o título e a descrição para publicar.",

        // Botón Activar / Detener Asistente
        "ACTIVAR" to "ATIVAR",
        "DETENER" to "PARAR",
        "ASISTENTE ONLINE" to "ASSISTENTE ONLINE",
        "ASISTENTE OFFLINE" to "ASSISTENTE OFFLINE",
        "Toca para iniciar" to "Toque para iniciar",
        "Toca para finalizar" to "Toque para encerrar",
        "Presiona ACTIVAR para iniciar el Asistente Flotante" to "Pressione ATIVAR para iniciar o Assistente Flutuante",
        "Asistente Hextech Activo • Toca la cámara flotante" to "Assistente Hextech Ativo • Toque na câmera flutuante",

        // Meta Oficial & Rankings
        "Servidor Chino (Tencent / LOLM)" to "Estatísticas do Meta Oficial",
        "Meta Oficial en Vivo" to "Meta Oficial Ao Vivo",
        "Estadísticas del Meta Oficial" to "Estatísticas do Meta Oficial",
        "Estadísticas Oficiales del Meta" to "Estatísticas Oficiais do Meta",
        "Estadísticas Servidor CN (Tencent)" to "Estatísticas do Meta Oficial",
        "Win Rate, Pick, Ban y Variación Diaria (Vs. Ayer)" to "Win Rate, Pick, Ban e Tendência em Tempo Real",
        "Win Rate, Pick, Ban y Tendencia en Tiempo Real" to "Win Rate, Pick, Ban e Tendência em Tempo Real",
        "Tendencia en Vivo" to "Tendência Ao Vivo",
        "En Tiempo Real" to "Em Tempo Real",
        "Sincronizar" to "Sincronizar",
        "Sincronizando..." to "Sincronizando...",
        " Sincronizando estadísticas oficiales..." to " Sincronizando estatísticas oficiais...",
        " En vivo:" to " Ao vivo:",
        "️ Datos en caché local:" to "️ Dados em cache local:",
        "Instantáneo 24/7" to "Instantâneo 24/7",
        "Rango Activo:" to "Elo Ativo:",
        "Retador / Soberano" to "Desafiante / Soberano",
        "Retador/Soberano" to "Desafiante / Soberano",
        "Maestro / Gran Maestro" to "Mestre / Grão-Mestre",
        "Maestro/Gran Maestro" to "Mestre / Grão-Mestre",
        "Gran Maestro / Maestro+" to "Grão-Mestre / Mestre+",
        "Esmeralda / Diamante" to "Esmeralda / Diamante",
        "Esmeralda/Diamante" to "Esmeralda / Diamante",
        "General" to "Geral",
        "General (Todas las Ligas)" to "Geral (Todas as Ligas)",
        "Soberano" to "Soberano",
        "Maestro+" to "Mestre+",
        "Diamante+" to "Diamante+",
        "Todas las Ligas" to "Todas as Ligas",
        "Todas" to "Todas",
        "Todos los Roles" to "Todas as Funções",
        "Todas las Líneas" to "Todas as Rotas",
        "Buscar campeón por nombre o habilidad..." to "Buscar campeão por nome ou habilidade...",
        "Limpiar" to "Limpar",
        "Vs. Ayer" to "Tendência Ao Vivo",
        "Tasa de Victoria" to "Taxa de Vitória",
        "Tasa de Selección" to "Taxa de Escolha",
        "Tasa de Bloqueo" to "Taxa de Banimento",
        "Elegir como mi Pick" to "Escolher como meu Pick",
        "SELECCIONAR MI PICK PARA" to "SELECIONAR MEU PICK PARA",
        "TU ELECCIÓN EN" to "SUA ESCOLHA NA",
        "Cambiar línea" to "Mudar rota",

        // Runas Clave
        "Electrocutar" to "Eletrocutar",
        "Cosecha Oscura" to "Colheita Sombria",
        "Fortalecimiento" to "Fortalecimento",
        "Compás Letal" to "Ritmo Fatal",
        "Pies Veloces" to "Agilidade nos Pés",
        "Conquistador" to "Conquistador",
        "Garras del Inmortal" to "Aperto dos Mortos-Vivos",
        "Guardián" to "Guardião",
        "Aery" to "Aery",
        "Cometa Arcano" to "Cometa Arcano",
        "Irrupción de Fase" to "Ímpeto Gradual",
        "Primer Golpe" to "Primeiro Ataque",
        "Soberano Gélido" to "Soberano Gélido",

        // Runas de Brujería (Sorcery)
        "Arcanólogo Axiomático" to "Arcanologista Axiomático",
        "Banda de Maná" to "Faixa de Fluxo de Mana",
        "Botanista" to "Botanista",
        "Hextello" to "Hexflashtração",
        "Trascendencia" to "Transcendência",
        "Celeridad" to "Celeridade",
        "Concentración Absoluta" to "Foco Absoluto",
        "Piroláser" to "Chamuscar",
        "Capa del Nimbo" to "Manto de Nimbus",
        "Se Avecina Tormenta" to "Tempestade Crescente",
        "Semillero Ixtalí" to "Sementeira Ixtali",
        "PermisoSuperposicionTexto" to "1. Toque em 'Conceder Permissão'.\n2. Ative o interruptor para o Coach.\n3. Volte ao aplicativo e pressione ATIVAR.",
        "release_notes_fallback" to "• Otimizações de desempenho no assistente inteligente.\n• Atualização de sinergias e counters para o patch atual de Wild Rift.\n• Melhorias na interface e navegação rápida.",
        "1. Permiso de Superposición" to "1. Permissão de Sobreposição",
        "2. Desactivar Ahorro de Batería" to "2. Desativar Economia de Bateria",
        "3. Temas y Barra de Navegación" to "3. Temas e Barra de Navegação",
        "4. Estado del Servidor" to "4. Status do Servidor",
        "ACTIVO" to "ATIVO",
        "Abrir Panel de Administrador" to "Abrir Painel de Administrador",
        "Barra Inferior" to "Barra Inferior",
        "Barra:" to "Barra:",
        "Bugs" to "Bugs",
        "Buscar objeto..." to "Buscar item...",
        "Buscar por título, contenido o modelo..." to "Buscar por título, conteúdo ou modelo...",
        "Buzón de Reportes & Ideas" to "Caixa de Relatórios & Ideias",
        "Calculadora de Daño & Penetración" to "Calculadora de Dano & Penetração",
        "Cambiar Tema" to "Mudar Tema",
        "Cargando reportes..." to "Carregando relatórios...",
        "Cerrando..." to "Fechando...",
        "Completado" to "Concluído",
        "Completados" to "Concluídos",
        "Configuración para Segundo Plano" to "Configuração para Segundo Plano",
        "Counter Pick" to "Counter Pick",
        "Descarga Finalizada" to "Download Concluído",
        "Descargando Recursos" to "Baixando Recursos",
        "Descargar Recursos" to "Baixar Recursos",
        "Describe qué sucedió o cómo reproducir el error..." to "Descreva o que aconteceu ou como reproduzir o erro...",
        "Describe tu idea o mejora para la aplicación..." to "Descreva sua ideia ou melhoria para o aplicativo...",
        "Detener Flotante" to "Parar Flutuante",
        "Dispositivo:" to "Dispositivo:",
        "ELEGIR" to "ESCOLHER",
        "Ej: El overlay no detecta la pantalla de selección" to "Ex: O overlay não detecta a tela de seleção",
        "Elige tu estética visual y barra de navegación" to "Escolha sua estética visual e barra de navegação",
        "Enviando mensaje..." to "Enviando mensagem...",
        "Enviar reporte" to "Enviar relatório",
        "Enviar sugerencia" to "Enviar sugestão",
        "Envía tus reportes de fallos o sugerencias para seguir mejorando la aplicación:" to "Envie seus relatórios de bugs ou sugestões para continuar melhorando o app:",
        "Error al cargar:" to "Erro ao carregar:",
        "Esta acción borrará permanentemente el reporte:" to "Esta ação excluirá permanentemente o relatório:",
        "Gestión de Mensajes & Reportes" to "Gestão de Mensagens & Relatórios",
        "Ideas" to "Ideias",
        "Lanzar Flotante en Juego" to "Iniciar Flutuante no Jogo",
        "Los nuevos mensajes enviados por los usuarios aparecerán aquí." to "Novas mensagens enviadas pelos usuários aparecerão aqui.",
        "MEJOR OPCIÓN" to "MELHOR OPÇÃO",
        "Marcar como Completado" to "Marcar como Concluído",
        "No hay reportes en esta categoría" to "Nenhum relatório nesta categoria",
        "No hay reportes registrados" to "Nenhum relatório registrado",
        "ONLINE" to "ONLINE",
        "Objetos Oficiales" to "Itens Oficiais",
        "Panel de Administrador" to "Painel de Administrador",
        "Para que el asistente flote en tiempo real sobre tu partida de Wild Rift sin que Android cierre el proceso por consumo de memoria:" to "Para que o assistente flutue em tempo real sobre sua partida de Wild Rift sem que o Android feche o processo por consumo de memória:",
        "Personaliza el aspecto de la aplicación seleccionando entre múltiples temas inspirados en las regiones de Runaterra y configurando la paleta de colores de la barra de navegación." to "Personalize a aparência do aplicativo selecionando entre vários temas inspirados nas regiões de Runeterra e configurando a paleta de cores da barra de navegação.",
        "Personalización de Temas" to "Personalização de Temas",
        "Por resolver" to "Pendente",
        "Rama" to "Ramo",
        "Reabrir (Marcar por resolver)" to "Reabrir (Marcar como pendente)",
        "Recomendaciones para funcionamiento óptimo sobre Wild Rift" to "Recomendações para funcionamento ideal sobre o Wild Rift",
        "Reintentar" to "Tentar novamente",
        "Salir" to "Sair",
        "Selecciona un color para la barra inferior:" to "Selecione uma cor para a barra inferior:",
        "Selecciona un tema para transformar la paleta de colores, fondos y acentos de toda la aplicación." to "Selecione um tema para transformar a paleta de cores, fundos e destaques de todo o aplicativo.",
        "Tema actual:" to "Tema atual:",
        "Temas (13)" to "Temas (13)",
        "Heal" to "Curar",
        "Smite" to "Aplastar",
        "Ignite" to "Prender",
        "Flash" to "Destello",
        "Ghost" to "Fantasmal",
        "Barrier" to "Barrera",
        "Exhaust" to "Extenuación",
        "Cleanse" to "Limpiar",
        "Teleport" to "Teleportar",
        "Clarity" to "Claridad",
        "Mark / Dash" to "Marca y Deslizamiento",

        "Total" to "Total",
        "Ver detalles ▾" to "Ver detalhes ▾",
        "Versión App:" to "Versão do App:",
        "Vista previa en tiempo real" to "Prévia em tempo real",
        "¿Eliminar este reporte?" to "Excluir este relatório?",
        "¿Estás seguro de que deseas cerrar Coach? Se cerrarán los asistentes activos." to "Tem certeza de que deseja fechar o Coach? Os assistentes ativos serão encerrados.",
        "¿Salir de la aplicación?" to "Sair do aplicativo?",
        "↓ Desliza para cerrar" to "↓ Deslize para fechar",
        " Concedido (Ventana flotante habilitada)" to " Concedido (Janela flutuante ativada)",
        " Sin restricciones (No se cerrará en segundo plano)" to " Sem restrições (Não fechará em segundo plano)",
        " Optimizado: Toca para quitar restricción" to " Otimizado: Toque para remover restrição",
        " Pendiente: Toca para autorizar" to " Pendente: Toque para autorizar",
        " Dispositivo:" to " Dispositivo:",
        "Hextech Piltover" to "Hextech Piltover",
        "Piltover" to "Piltover",
        "Estilo oficial Hextech dorado y cian sobre fondo oscuro profundo." to "Estilo oficial Hextech dourado e ciano sobre fundo escuro profundo.",
        "Noxus Carmesí" to "Noxus Carmesim",
        "Noxus" to "Noxus",
        "Fuerza militar implacable con tonos rojo sangre, acero y oro bélico." to "Força militar implacável com tons vermelho-sangue, aço e ouro bélico.",
        "Zaun Quimtech" to "Zaun Quimtec",
        "Zaun" to "Zaun",
        "Energía radioactiva ácida con verde neón, vapores y cian industrial." to "Energia radioativa ácida com verde neon, vapores e ciano industrial.",
        "Jonia Espiritual" to "Ionia Espiritual",
        "Jonia" to "Ionia",
        "Armonía floral de loto con rosa cerezo, místico y oro ancestral." to "Harmonia floral de lótus com rosa cerejeira, místico e ouro ancestral.",
        "Shurima Solar" to "Shurima Solar",
        "Shurima" to "Shurima",
        "Gloria del disco solar con oro brillante, arena ardiente y ámbar." to "Glória do disco solar com ouro brilhante, areia ardente e âmbar.",
        "Freljord Glacial" to "Freljord Glacial",
        "Freljord" to "Freljord",
        "Frío helado de las montañas con azul hielo cristalino y nieve pura." to "Frio congelante das montanhas com azul gelo cristalino e neve pura.",
        "Aguas Estancadas" to "Águas de Sentina",
        "AguasTurbias" to "Águas de Sentina",
        "Mareas piratas profundas con verde marino, olas y oro maldito." to "Marés piratas profundas com verde-marinho, ondas e ouro amaldiçoado.",
        "Monte Targón Astral" to "Monte Targon Astral",
        "Targón" to "Targon",
        "Cosmos estelar divino con violeta estelar, constelaciones y plata astral." to "Cosmos estelar divino com violeta estelar, constelações e prata astral.",
        "Islas de la Sombra" to "Ilhas das Sombras",
        "IslasSombras" to "Ilhas das Sombras",
        "Niebla negra espectral con verde espectro, almas atrapadas y obsidiana." to "Névoa negra espectral com verde espectro, almas aprisionadas e obsidiana.",
        "Demacia Real" to "Demacia Real",
        "Demacia" to "Demacia",
        "Justicia impecable con azul real pétreo, oro pulido y mármol." to "Justiça impecável com azul real petrificado, ouro polido e mármore.",
        "El Vacío Cósmico" to "O Vazio Cósmico",
        "Vacío" to "Vazio",
        "Entropía dimensional abisal con púrpura cósmico, fucsia alienígena y oscuridad." to "Entropia dimensional abissal com púrpura cósmico, fúcsia alienígena e escuridão.",
        "Ciudad de Bandle" to "Bandópolis",
        "Bandle" to "Bandópolis",
        "Magia yordle alegre con arcoíris místico, dorado miel y azul cielo." to "Magia yordle alegre com arco-íris místico, dourado mel e azul celeste.",
        "Hextech Día (Claro)" to "Hextech Dia (Claro)",
        "Modo Claro" to "Modo Claro",
        "Interfaz diurna de alto contraste con blanco puro y acentos dorados." to "Interface diurna de alto contraste com branco puro e detalhes dourados.",
        "Automático (Igual al Tema)" to "Automático (Igual ao Tema)",
        "Sigue dinámicamente el tema actual" to "Segue dinamicamente o tema atual",
        "Hextech Dorado" to "Hextech Dourado",
        "Elegante oro piltover" to "Elegante ouro de Piltover",
        "Hextech Cian" to "Hextech Ciano",
        "Resplandor cian arcano" to "Brilho ciano arcano",
        "Rojo carmesí bélico" to "Vermelho carmesim de guerra",
        "Zaun Neón" to "Zaun Neon",
        "Verde tóxico radioactivo" to "Verde tóxico radioativo",
        "Jonia Loto" to "Ionia Lótus",
        "Rosa cerezo espiritual" to "Rosa cerejeira espiritual",
        "Shurima Ámbar" to "Shurima Âmbar",
        "Dorado ardiente solar" to "Dourado ardente solar",
        "Freljord Escarcha" to "Freljord Geada",
        "Azul glacial de hielo puro" to "Azul glacial de gelo puro",
        "Aguas Profundas" to "Águas Profundas",
        "Verde marino abisal" to "Verde marinho abissal",
        "Targón Cósmico" to "Targon Cósmico",
        "Púrpura astral celestial" to "Púrpura astral celestial",
        "Espectro Sombrío" to "Espectro Sombrio",
        "Verde alma espectral" to "Verde alma espectral",
        "Demacia Petricita" to "Demacia Petricita",
        "Azul real y oro noble" to "Azul real e ouro nobre",
        "Vacío Abisal" to "Vazio Abissal",
        "Fucsia y violeta alienígena" to "Fúcsia e violeta alienígena",
        "Bandle Mágico" to "Bandópolis Mágica",
        "Lavanda y arcoíris yordle" to "Lavanda e arco-íris yordle",

        // === OBJETIVOS DE MAPA (PORTUGUÊS) ===
        "Dragón Infernal (Fuego)" to "Dragão Infernal (Fogo)",
        "Dragón de Montaña (Tierra)" to "Dragão da Montanha (Terra)",
        "Dragón de los Océanos (Agua)" to "Dragão dos Oceanos (Água)",
        "Dragón de Hielo (Glacial)" to "Dragão de Gelo (Glacial)",
        "Dragón Anciano (Elder Dragon)" to "Dragão Ancião (Elder Dragon)",
        "Heraldo de la Grieta (Rift Herald)" to "Arauto do Vale (Rift Herald)",
        "Barón Nashor" to "Barão Nashor",
        "Cangrejo Escurridizo" to "Aronguejo",
        "Ancestro Ígneo (Buff Rojo)" to "Rubrivira (Buff Vermelho)",
        "Coloso Celeste (Buff Azul)" to "Sentinela Azul (Buff Azul)",
        "Minuto 0:20" to "Minuto 0:20",
        "Minuto 1:25" to "Minuto 1:25",
        "Minuto 4:00" to "Minuto 4:00",
        "Minuto 5:00" to "Minuto 5:00",
        "Minuto 12:00" to "Minuto 12:00",
        "Reaparece cada 4:00" to "Ressurge a cada 4:00",
        "Reaparece cada 5:00" to "Ressurge a cada 5:00",
        "Reaparece cada 2:30" to "Ressurge a cada 2:30",
        "Solo aparece 1 por partida" to "Apenas 1 por partida",
        "Monstruos Épicos & Tiempos de Aparición" to "Monstros Épicos & Tempos de Surgimento",
        "Conocer los tiempos exactos de aparición en Wild Rift asegura la victoria de tu equipo:" to "Conhecer os tempos exatos de surgimento no Wild Rift garante a vitória da sua equipe:",
        "Otorga a todo el equipo +3% de daño de ataque y +3% de poder de habilidad acumulable." to "Concede a toda a equipe +3% de dano de ataque e +3% de poder de habilidade acumulável.",
        "Otorga a todo el equipo +6% de armadura y resistencia mágica adicionales." to "Concede a toda a equipe +6% de armadura e resistência mágica adicionais.",
        "Restaura un 2.5% de la vida faltante cada 5 segundos a todos los miembros del equipo." to "Restaura 2,5% da vida perdida a cada 5 segundos para todos os membros da equipe.",
        "Otorga +7 de aceleración de habilidad a todo el equipo y crea zonas de escarcha." to "Concede +7 de aceleração de habilidade para toda a equipe e cria zonas de gelo.",
        "Ataques y habilidades queman a los rivales. Si la vida del rival cae por debajo del 15%, es ejecutado de inmediato." to "Ataques e habilidades queimam os inimigos. Se a vida cair abaixo de 15%, é executado imediatamente.",
        "Al recoger el Ojo del Heraldo, permite invocar al Heraldo para embestir y destruir placas de torretas enemigas." to "Ao pegar o Olho do Arauto, permite invocar o Arauto para investir e destruir placas de torres inimigas.",
        "Otorga Mano del Barón: potencia el daño de los súbditos aliados cercanos y reduce el tiempo de Retirada a 4 segundos." to "Concede Mão do Barão: fortalece tropas aliadas próximas e reduz o tempo de Retorno para 4 segundos.",
        "Genera un Santuario de Velocidad y visión inquebrantable en el río frente al Dragón o Barón." to "Gera um Santuário de Velocidade e visão no rio em frente ao Dragão ou Barão.",
        "Otorga Escudo de Cenizas: ataques básicos queman causando daño verdadero periódico y ralentizan." to "Concede Brasas de Cinzas: ataques básicos queimam causando dano verdadeiro periódico e lentidão.",
        "Otorga Perspicacia Espiritual: regeneración masiva de maná/energía y aceleración de habilidad adicional." to "Concede Perspicácia Espiritual: regeneração massiva de mana/energia e aceleração de habilidade adicional.",
        "Prioriza asegurar la línea de dragón empujando oleadas 30s antes de su aparición. Ideal para composiciones de daño explosivo." to "Priorize puxar a rota do dragão 30s antes do surgimento. Ideal para composições de dano explosivo.",
        "Refuerza la línea frontal de los tanques, facilitando asedios prolongados bajo torre enemiga." to "Fortalece a linha de frente dos tanques, facilitando cercos prolongados sob torres inimigas.",
        "Otorga sustain inagotable en el mapa para desgastar al rival sin necesidad de volver a base." to "Fornece sustentação infinita no mapa para desgastar o rival sem precisar voltar à base.",
        "Permite rotar habilidades mucho más rápido en escaramuzas y peleas por el Barón." to "Permite usar habilidades muito mais rápido em escaramuças e lutas pelo Barão.",
        "El buff más decisivo de Wild Rift en el juego tardío. Asegura visión perimetral con centinelas antes de iniciar." to "O bônus mais decisivo de Wild Rift no fim do jogo. Garanta visão com sentinelas antes de iniciar.",
        "Úsalo en la línea de Barón o Mid para derribar la primera torreta y desbloquear rotaciones tempranas." to "Use na rota do Barão ou Meio para derrubar a primeira torre e liberar rotações rápidas.",
        "Aprovecha el buff para asediar las tres líneas simultáneamente y forzar la caída de torres de inhibidor." to "Aproveite o bônus para cercar as três rotas simultaneamente e forçar a queda dos inibidores.",
        "Aplica control de masas duro para romper su escudo de inmediato y acelerar la limpieza del río." to "Aplique controle de grupo forte para quebrar o escudo de imediato e acelerar o abate no rio.",
        "Esencial para tiradores y junglas físicos para aumentar el potencial de persecución y hostigamiento." to "Essencial para atiradores e caçadores físicos aumentarem o potencial de perseguição e poke.",
        "Cédelo a tu carrilero central mágico para asegurar empuje continuo de oleadas antes de los objetivos." to "Doe ao seu campeão mágico do meio para garantir empurrão contínuo de tropas antes dos objetivos.",

        // === HECHIZOS DE INVOCADOR (PORTUGUÊS) ===
        "Fantasmal" to "Fantasma",
        "Curar" to "Curar",
        "Barrera" to "Barreira",
        "Extenuación" to "Exaustão",
        "Limpiar" to "Purificar",
        "Destello" to "Flash",
        "Prender" to "Incendiar",
        "Aplastar" to "Golpear",
        "Castigo" to "Golpear",
        "Teleportar" to "Teleporte",
        "Claridad" to "Clareza",
        "Marca y Deslizamiento" to "Marca / Avanço",
        "Marca" to "Marca",
        "Movilidad & Utilidad" to "Mobilidade & Utilidade",
        "Combate & Daño" to "Combate & Dano",
        "Movilidad & Utilidad / Defensivo" to "Mobilidade & Defensivo",
        "Daño / Combate" to "Dano / Combate",
        "Enfriamiento:" to "Tempo de Recarga:",
        " Recomendación de Invocador:" to " Recomendação de Invocador:",
        "Imprescindible en el 99% de las partidas para reposicionarse, iniciar peleas de equipo o escapar por encima de muros." to "Indispensável em 99% das partidas para se reposicionar, iniciar lutas de equipe ou fugir por paredes.",
        "Clave para asesinos y soportes agresivos para asegurar asesinatos en juego temprano y anular curaciones de campeones como Aatrox, Soraka o Dr. Mundo." to "Fundamental para assassinos e suportes agressivos garantirem abates no início do jogo e anularem curas de Aatrox, Soraka ou Dr. Mundo.",
        "Obligatorio para el rol de Jungla para asegurar monstruos épicos (Dragones, Heraldo, Barón) y farmear eficientemente." to "Obrigatório para a Selva para garantir monstros épicos (Dragões, Arauto, Barão) e farmar com eficiência.",
        "Vital para neutralizar a hipercarries o asesinos rivales en peleas grupales reduciendo su daño y movilidad drásticamente." to "Vital para neutralizar hipercarregadores ou assassinos rivais em lutas de equipe, reduzindo drasticamente seu dano e mobilidade.",
        "Excelente para tiradores o magos de ráfaga para resistir emboscadas o burst sorpresa en línea." to "Excelente para atiradores ou magos de dano explosivo sobreviverem a emboscadas na rota.",
        "Ideal para campeones con movilidad continua como Darius, Olaf, Singed o Gwen para evitar que los enemigos escapen." to "Ideal para campeões com mobilidade contínua como Darius, Olaf, Singed ou Gwen para evitar que inimigos escapem.",
        "Potente para campeones de carril de Barón para mantener presión dividida y unirse inmediatamente a peleas de objetivos." to "Poderoso para a rota do Barão manter pressão dividida e entrar imediatamente nas lutas por objetivos.",
        "Uso situacional según la composición y mapa." to "Uso situacional de acordo com a composição e mapa.",
        "Obtienes un gran aumento de velocidad de movimiento que disminuye a lo largo de 8 s. Las eliminaciones aumentan la duración de la mejora y reinician la velocidad de movimiento." to "Recebe um grande aumento de velocidade de movimento que decai ao longo de 8s. Abates estendem a duração e reiniciam a velocidade.",
        "Restaura vida y otorga velocidad de movimiento a ti y al campeón aliado más cercano." to "Restaura vida e concede velocidade de movimento para você e o campeão aliado mais ferido.",
        "Obtienes un escudo que absorbe daño durante 2 s." to "Ganha um escudo que absorve dano durante 2s.",
        "Extenúa al campeón enemigo objetivo, lo que reduce su velocidad de movimiento y el daño que inflige durante 2.5 s." to "Exaure o campeão inimigo alvo, reduzindo sua velocidade de movimento e dano causado por 2,5s.",
        "Elimina todas las debilitaciones (excepto levantamientos y supresiones) y otorga tenacidad durante 1.5 s." to "Remove todos os efeitos negativos de controle de grupo e concede tenacidade por 1,5s.",
        "Teleporta a tu campeón una corta distancia hacia la posición objetivo." to "Teletransporta seu campeão por uma curta distância na direção do cursor.",
        "Prende al campeón enemigo objetivo, lo que inflige daño verdadero a lo largo de 5 s y le aplica Heridas graves." to "Incendeia o campeão inimigo alvo, causando dano verdadeiro ao longo de 5s e aplicando Feridas Dolorosas.",
        "Inflige daño verdadero a un monstruo de la jungla o súbdito enemigo. Restaura vida al usarlo contra monstruos." to "Causa dano verdadeiro a um monstro da selva ou tropa inimiga. Restaura vida ao usar contra monstros.",
        "Tras canalizar durante 3.5 s, te teleportas a una estructura, súbdito o centinela aliado." to "Após canalizar por 3,5s, teletransporta-se para uma estrutura, tropa ou sentinela aliada.",
        "Restaura maná a ti y a los aliados cercanos." to "Restaura mana para você e aliados próximos.",
        "Lanza una bola de nieve en línea recta. Si impacta, puedes reactivar para deslizarte hacia el objetivo." to "Lança uma bola de neve em linha reta. Se atingir, reative para avançar até a unidade inimiga.",

        // === RUNAS (PORTUGUÊS) ===
        "Runa Clave" to "Runa Chave",
        "Clave" to "Chave",
        "Precisión" to "Precisão",
        "Dominación" to "Dominação",
        "Valor" to "Determinação",
        "Brujería" to "Feitiçaria",
        "Inspiración" to "Inspiração",
        "Electrocutar" to "Eletrocutar",
        "Aery" to "Invocar Aery",
        "Invocar a Aery" to "Invocar Aery",
        "Conquistador" to "Conquistador",
        "Pies Veloces" to "Agilidade nos Pés",
        "Garras del Inmortal" to "Aperto dos Mortos-Vivos",
        "Réplica" to "Pós-choque",
        "Irrupción de Fase" to "Ímpeto Gradual",
        "Primer Golpe" to "Primeiro Ataque",
        "Cadencia Letal" to "Ritmo Fatal",
        "Compás Letal" to "Ritmo Fatal",
        "Cometa Arcano" to "Cometa Arcano",
        "Cosecha Oscura" to "Colheita Sombria",
        "Guardián" to "Guardião",
        "Soberano Gélido" to "Aprimoramento Glacial",
        "Fortalecimiento" to "Mata-Cráquens",
        "Triunfo" to "Triunfo",
        "Golpe de Gracia" to "Golpe de Misericórdia",
        "Derribado" to "Dilacerar",
        "Último Esfuerzo" to "Até a Morte",
        "Leyenda: Presteza" to "Lenda: Espontaneidade",
        "Leyenda: Tenacidad" to "Lenda: Tenacidade",
        "Leyenda: Linaje" to "Lenda: Linhagem",
        "Fervor de Batalla" to "Fervor da Batalha",
        "Impacto Súbito" to "Impacto Repentino",
        "Marca de la Muerte" to "Marca da Morte",
        "Golpe Bajo" to "Golpe Desleal",
        "Colección de Ojos" to "Globos Oculares",
        "Cazador Ingenioso" to "Caça Ardilosa",
        "Cazador Incansable" to "Caça Incansável",
        "Cazador Definitivo" to "Caça Suprema",
        "Centinela Zombi" to "Sentinela Zumbi",
        "Poro Fantasma" to "Poro Fantasma",
        "Coraza Ósea" to "Osso Revestido",
        "Segundo Aire" to "Ventos Revigorantes",
        "Condicionamiento" to "Condicionamento",
        "Sobrecrecimiento" to "Crescimento Excessivo",
        "Revitalizar" to "Revitalizar",
        "Inquebrantable" to "Inabalável",
        "Fuerza Adaptable" to "Força Adaptativa",
        "Banda de Maná" to "Faixa de Fluxo de Mana",
        "Banda de Flujo" to "Faixa de Fluxo de Mana",
        "Trascendencia" to "Transcendência",
        "Tormenta Creciente" to "Tempestade Crescente",
        "Celeridad" to "Celeridade",
        "Caminar sobre el Agua" to "Caminhar Sob as Águas",
        "Orbe Anulador" to "Orbe Anulador",
        "Capa del Nimbo" to "Manto de Nimbus",
        "Calzado Mágico" to "Calçados Mágicos",
        "Perspicacia Cósmica" to "Perspicácia Cósmica",
        "Entrega de Galletas" to "Entrega de Biscoitos",
        "Demolición" to "Demolir",
        "Fuente de Vida" to "Fonte da Vida",
        "Destello Hextech" to "Flashtração Hextec",
        "Mercado de Futuros" to "Mercado do Futuro",
        "Desmaterializador" to "Desmaterializador de Tropas",
        "Tónico de Distorsión" to "Tônico de Distorção no Tempo",
        "Dulces Frutos" to "Gula",
        " Consejo del Coach:" to " Conselho do Coach:",
        " Ideal para combos cortos de asesinos o magos que buscan estallar a un rival rápido." to " Ideal para combos rápidos de assassinos ou magos que buscam explodir um rival rapidamente.",
        " Perfecto para campeones que escalan y aseguran asesinatos en peleas largas (ej. Katarina, Khazix)." to " Perfeito para campeões que escalam e garantem abates em lutas longas (ex: Katarina, Kha'Zix).",
        " Excelente para tiradores o luchadores que dependen de ataques básicos rápidos." to " Excelente para atiradores ou lutadores que dependem de ataques básicos rápidos.",
        " Fundamental en hypercarries como Jinx o Vayne para dominar las peleas largas." to " Fundamental em hipercarregadores como Jinx ou Vayne para dominar lutas longas.",
        " Útil para sobrevivir líneas difíciles gracias a su curación y movilidad al kitear." to " Útil para sobreviver a rotas difíceis graças à sua cura e mobilidade ao caitar.",
        " La mejor opción para luchadores y duelistas que buscan intercambios prolongados (ej. Darius, Riven)." to " A melhor opção para lutadores e duelistas que buscam trocas prolongadas (ex: Darius, Riven).",
        " Indispensable en tanques y colosos para tener sustain y escalar vida máxima." to " Indispensável em tanques e colossos para ter sustentação e escalar vida máxima.",
        " Selecciona esta runa en soportes protectores (ej. Braum, Lulu) para mitigar burst enemigo." to " Selecione esta runa em suportes protetores (ex: Braum, Lulu) para mitigar dano explosivo.",
        " Muy versátil para soportes encantadores o magos de pokeo constante (ej. Karma, Orianna)." to " Muito versátil para suportes encantadores ou magos de poke constante (ex: Karma, Orianna).",
        " Ideal para magos de artillería que pokean a distancia (ej. Ziggs, Lux)." to " Ideal para magos de artilharia que dão poke à distância (ex: Ziggs, Lux).",
        " Perfecta para magos de combo que necesitan reposicionarse rápido (ej. Orianna, Vladimir)." to " Perfeita para magos de combo que precisam se reposicionar rápido (ex: Orianna, Vladimir).",
        " Útil en asesinos o magos de ráfaga para escalar en oro rápidamente y explotar objetivos." to " Útil em assassinos ou magos de explosão para escalar ouro rapidamente e explodir alvos.",
        " Excelente para soportes de iniciación (ej. Leona, Nautilus) para potenciar su CC." to " Excelente para suportes de iniciação (ex: Leona, Nautilus) para potencializar seu controle de grupo.",
        " Runa perfecta para tanques de iniciación masiva (ej. Amumu, Alistar) que necesitan resistir el focus enemigo post-combo." to " Runa perfeita para tanques de iniciação em massa (ex: Amumu, Alistar) que precisam resistir ao foco inimigo após o combo.",
        " Ideal en peleas de equipo cerradas. Te recompensa con vida vital tras cada eliminación o asistencia." to " Ideal em lutas de equipe acirradas. Recompensa você com vida vital após cada abate ou assistência.",
        " Útil en intercambios sostenidos cortos, incrementa tu daño para asegurar duelos tempranos." to " Útil em trocas sustentadas curtas, aumenta seu dano para garantir duelos no início.",
        " Obligatorio si el equipo enemigo tiene muchos tanques y campeones con mucha vida extra." to " Obrigatório se a equipe inimiga tiver muitos tanques e campeões com muita vida adicional.",
        " Para asesinos o ADC que buscan asegurar la baja (ejecutar) a enemigos que intenten escapar a baja vida." to " Para assassinos ou ADCs que buscam abater inimigos com pouca vida tentando fugir.",
        " Escoge esta runa si priorizas maximizar tu DPS (daño por segundo) a través de ataques básicos rápidos." to " Escolha esta runa se priorizar maximizar seu DPS através de ataques básicos rápidos.",
        " Vital si el equipo enemigo está lleno de control de masas (Stun, Inmovilización, etc). Evitará que te eliminen encadenado." to " Vital se o time inimigo tiver muito controle de grupo (Atordoamentos, Enraizamentos). Evita combos de CC.",
        " Si tu campeón no armará Robo de Vida temprano pero necesita sustento para sobrevivir y farmear." to " Se o seu campeão não fizer Roubo de Vida cedo mas precisar de sustentação para sobreviver e farmar.",
        " Excelente en duelistas como Olaf o Tryndamere que se vuelven más letales cuando se acercan a la muerte." to " Excelente em duelistas como Olaf ou Tryndamere que ficam mais letais perto da morte.",
        " Runa situacional: Úsala para complementar el estilo de juego de tu campeón frente a esta composición específica." to " Runa situacional: Use para complementar o estilo de jogo do seu campeão contra esta composição específica."
    )
)

@Composable
fun tr(key: String): String {
    val lang = LocalLanguage.current
    return trStr(if (lang == "auto") "es" else lang, key)
}

fun trStr(lang: String, key: String): String {
    val effectiveLang = if (lang == "auto") "es" else lang
    if (effectiveLang == "es") {
        return translations["es"]?.get(key) ?: key
    }
    
    val direct = translations[effectiveLang]?.get(key)
    if (direct != null) return direct
    
    val dynamic = DynamicTranslations.get(effectiveLang, key)
    if (dynamic != null) return dynamic

    // --- REPOSITORY LOOKUP (PORTUGUÊS EM MANUTENÇÃO) ---
    val itemByName = WildRiftRepository.items.find { it.name.equals(key, ignoreCase = true) }
    if (itemByName != null && itemByName.namePt.isNotBlank()) return itemByName.namePt
    
    val itemByStats = WildRiftRepository.items.find { it.stats.equals(key, ignoreCase = true) }
    if (itemByStats != null && itemByStats.statsPt.isNotBlank()) return itemByStats.statsPt
    
    val itemByPassive = WildRiftRepository.items.find { it.passive.equals(key, ignoreCase = true) }
    if (itemByPassive != null && itemByPassive.passivePt.isNotBlank()) return itemByPassive.passivePt
    
    val champByName = WildRiftRepository.champions.find { it.name.equals(key, ignoreCase = true) }
    if (champByName != null && champByName.namePt.isNotBlank()) return champByName.namePt
    
    val runeByName = WildRiftRepository.runes.find { it.name.equals(key, ignoreCase = true) }
    if (runeByName != null && runeByName.namePt.isNotBlank()) return runeByName.namePt
    
    val spellByName = WildRiftRepository.summonerSpells.find { it.name.equals(key, ignoreCase = true) }
    if (spellByName != null && spellByName.namePt.isNotBlank()) return spellByName.namePt

    var replaced = key
    if (effectiveLang == "pt") {
        replaced = replaced.replace("Daño Físico", "Dano Físico", ignoreCase = true)
        replaced = replaced.replace("Daño Mágico", "Dano Mágico", ignoreCase = true)
        replaced = replaced.replace("Defensa", "Defesa", ignoreCase = true)
        replaced = replaced.replace("Magia", "Magia", ignoreCase = true)
        replaced = replaced.replace("Botas", "Botas", ignoreCase = true)
        replaced = replaced.replace("Básicos", "Básicos", ignoreCase = true)
        replaced = replaced.replace("Nivel Medio", "Nível Médio", ignoreCase = true)
        replaced = replaced.replace("Encantamientos", "Encantamentos", ignoreCase = true)
        replaced = replaced.replace("Parche", "Patch", ignoreCase = true)
        replaced = replaced.replace("Vida Máxima", "Vida Máxima", ignoreCase = true)
        replaced = replaced.replace("Daño de Ataque", "Dano de Ataque", ignoreCase = true)
        replaced = replaced.replace("Poder de Habilidad", "Poder de Habilidade", ignoreCase = true)
        replaced = replaced.replace("Velocidad de Ataque", "Velocidade de Ataque", ignoreCase = true)
        replaced = replaced.replace("Velocidad de Movimiento", "Velocidade de Movimento", ignoreCase = true)
        replaced = replaced.replace("Aceleración de Habilidad", "Aceleração de Habilidade", ignoreCase = true)
        replaced = replaced.replace("Probabilidad de Crítico", "Chance de Crítico", ignoreCase = true)
        replaced = replaced.replace("Daño Crítico", "Dano Crítico", ignoreCase = true)
        replaced = replaced.replace("Penetración de Armadura", "Penetração de Armadura", ignoreCase = true)
        replaced = replaced.replace("Penetración Mágica", "Penetração Mágica", ignoreCase = true)
        replaced = replaced.replace("Resistencia Mágica", "Resistência Mágica", ignoreCase = true)
        replaced = replaced.replace("Armadura", "Armadura", ignoreCase = true)
        replaced = replaced.replace("Robo de Vida", "Roubo de Vida", ignoreCase = true)
        replaced = replaced.replace("Omnivampirismo", "Omnivamp", ignoreCase = true)
        replaced = replaced.replace("Vampirismo", "Vamp", ignoreCase = true)
        replaced = replaced.replace("Daño Verdadero", "Dano Verdadeiro", ignoreCase = true)
        replaced = replaced.replace("Curación", "Cura", ignoreCase = true)
        replaced = replaced.replace("Escudo", "Escudo", ignoreCase = true)
        replaced = replaced.replace("Enfriamiento", "Tempo de Recarga", ignoreCase = true)
        replaced = replaced.replace("Pasiva", "Passiva", ignoreCase = true)
        replaced = replaced.replace("Habilidad", "Habilidade", ignoreCase = true)
        replaced = replaced.replace("Definitiva", "Ultimate", ignoreCase = true)
        replaced = replaced.replace("Inflige", "Causa", ignoreCase = true)
        replaced = replaced.replace("Aumenta", "Aumenta", ignoreCase = true)
        replaced = replaced.replace("Reduce", "Reduz", ignoreCase = true)
        replaced = replaced.replace("Otorga", "Concede", ignoreCase = true)
    }
    return replaced
}
