"""Authored champion constraints and choice-specific advice; no catalog text as advice."""
import csv
import re
from pathlib import Path

PROFILES = {row[0]: row[1:] for row in csv.reader(
    Path(__file__).with_name('champion_coaching_profiles.tsv').read_text().splitlines(), delimiter='|')}
MNEMONICS = {row[0]: row[1:] for row in csv.reader(
    Path(__file__).with_name('champion_coaching_mnemonics.tsv').read_text().splitlines(), delimiter='|')}
assert set(MNEMONICS) == set(PROFILES)

def profile(champion, pt=False):
    risk_es, risk_pt, rule_es, rule_pt = PROFILES[champion['id']]
    return (risk_pt, rule_pt) if pt else (risk_es, rule_es)

def overview(champion, lane, lane_name, translations, pt=False):
    risk, rule = profile(champion, pt)
    # Two independent execution steps, rather than copying an item or a spell.
    steps = rule.split('; ', 1)
    decision = steps[0].rstrip('.')
    detail = steps[-1][0].upper() + steps[-1][1:] if len(steps) == 2 else rule
    name = champion.get('namePt') or champion['name'].replace('Nunu y Willump', 'Nunu e Willump') if pt else champion['name']
    titles = ('Diagnóstico do erro/situação', 'Decisão Soberano', 'Micro e Macro detalhe', 'Regra aplicável') if pt else (
        'Diagnóstico del error/situación', 'Decisión Soberano', 'Micro y Macro detalle', 'Regla aplicable')
    lane_rules = {
        'TOP': ('El intercambio termina antes de perder la ruta a tu torre; prepara la compra con una oleada que alcance la torre rival.', 'A troca termina antes de perder a rota até sua torre; prepare a compra com uma onda que alcance a torre inimiga.'),
        'JUNGLE': ('Elige el campamento de salida por el siguiente objetivo y por la ruta que permite ejecutar esta secuencia, no por perseguir al primer rival.', 'Escolha o campo de saída pelo próximo objetivo e pela rota que permite executar esta sequência, não por perseguir o primeiro inimigo.'),
        'MID': ('Empuja antes de salir solo si puedes conservar la herramienta citada para el río; sin ella, termina la oleada y evita la entrada a ciegas.', 'Avance antes de sair apenas se puder preservar a ferramenta citada para o rio; sem ela, termine a onda e evite a entrada às cegas.'),
        'ADC': ('Mantén la distancia a tu protección durante esta secuencia; compra después de un crash o de un regreso coordinado con tu soporte.', 'Mantenha a distância até sua proteção durante esta sequência; compre depois de uma onda na torre ou de um retorno combinado com seu suporte.'),
        'SUPPORT': ('Tu salida de línea depende de la seguridad del tirador y del recurso citado; vuelve antes de que la oleada lo deje expuesto.', 'Sua saída da rota depende da segurança do atirador e do recurso citado; volte antes de a onda deixá-lo exposto.'),
    }
    return '\n'.join(f'{title}: {body}' for title, body in zip(titles, (
        f'{name} · {lane_name}. {risk}', decision + '.',
        detail + ' ' + lane_rules[lane][int(pt)], MNEMONICS[champion['id']][int(pt)])))

# Each choice answers a different combat problem. Values are decisions, not stat recitations.
ITEM_POLICIES = {
 'Eco de Luden': ('Necesitas convertir el primer impacto en presión sin gastar tu control para limpiar.', 'Precisa converter o primeiro acerto em pressão sem gastar seu controle para limpar.', 'Reserva la activación para el campeón cuando la siguiente disputa sea inminente.', 'Reserve a ativação para o campeão quando a próxima disputa estiver próxima.'),
 'Tormento de Liandry': ('El rival puede sobrevivir la primera rotación; necesitas mantener aplicaciones de daño mientras permanece en tu zona.', 'O inimigo pode sobreviver à primeira rotação; precisa manter aplicações de dano enquanto permanece na zona.', 'Compra por tiempo real de daño sobre vida alta; una entrada que termina al primer impacto no aprovecha la quemadura.', 'Compre pelo tempo real de dano contra vida alta; uma entrada encerrada no primeiro acerto não aproveita a queimadura.'),
 'Perdición del liche': ('La compra exige insertar un ataque después de una habilidad sin exponerte a la respuesta rival.', 'A compra exige inserir um ataque depois de uma habilidade sem expor você à resposta inimiga.', 'Habilidad y ataque seguro antes de otra habilidad; no cruces la protección solo por consumir el golpe.', 'Habilidade e ataque seguro antes de outra habilidade; não atravesse a proteção apenas para consumir o golpe.'),
 'Fuerza de trinidad': ('Tu secuencia debe dejar espacio para ataques entre habilidades y para moverte después del impacto.', 'Sua sequência deve abrir espaço para ataques entre habilidades e para mover após o acerto.', 'No gastes varias habilidades seguidas si puedes intercalar un ataque y conservar la salida.', 'Não gaste várias habilidades seguidas se puder intercalar um ataque e preservar a saída.'),
 'Guantelete de hielo': ('Necesitas que el ataque posterior a tu habilidad corte la ruta del rival y permita mantener el intercambio.', 'Precisa que o ataque depois da habilidade corte a rota inimiga e permita manter a troca.', 'Coloca la zona en la dirección de retirada; no persigas más allá de ella sin cobertura.', 'Coloque a zona na direção de retirada; não persiga além dela sem cobertura.'),
 'Segador de esencia': ('El recurso y el ataque tras habilidad deciden si puedes repetir tu rotación sin regresar a base.', 'O recurso e o ataque depois da habilidade decidem se consegue repetir a rotação sem voltar à base.', 'Completa el ataque posterior a la habilidad; repetir habilidades sin ese ataque pierde la devolución de maná.', 'Complete o ataque depois da habilidade; repetir habilidades sem esse ataque perde a devolução de mana.'),
 'Orbe infinito': ('Tu primer daño debe dejar al objetivo en el umbral de remate antes de comprometer la parte decisiva de la secuencia.', 'Seu primeiro dano deve deixar o alvo no limite de finalização antes de comprometer a parte decisiva da sequência.', 'Mira la vida restante después del daño inicial; no atribuyas la amplificación a un rival todavía sano.', 'Olhe a vida restante depois do dano inicial; não atribua a amplificação a um inimigo ainda saudável.'),
 'Sombrero mortal de Rabadon': ('Necesitas amplificar el poder de habilidad ya acumulado; adelantarlo no resuelve por sí solo maná, acceso ni defensa.', 'Precisa ampliar o poder de habilidade já acumulado; antecipar não resolve sozinho mana, acesso ou defesa.', 'Compra después de asegurar que puedes ejecutar tu rotación; más poder no recupera una habilidad fallada.', 'Compre depois de garantir que consegue executar a rotação; mais poder não recupera uma habilidade errada.'),
 'Bastón del Vacío': ('La resistencia mágica rival ya reduce tu rotación; otro objeto de poder puro puede rendir menos.', 'A resistência mágica inimiga já reduz sua rotação; outro item de poder puro pode render menos.', 'Verifica la resistencia de los objetivos que realmente puedes golpear antes de adelantar penetración.', 'Confira a resistência dos alvos que realmente consegue atingir antes de antecipar penetração.'),
 'Morellonomicón': ('La curación rival ocurre durante tu daño mágico y puede neutralizar el intercambio.', 'A cura inimiga ocorre durante seu dano mágico e pode neutralizar a troca.', 'Aplica daño cuando llegue la curación; no lo compres por un sanador al que tu rotación nunca alcanza.', 'Aplique dano quando a cura chegar; não compre por um curador que sua rotação nunca alcança.'),
 'Diente de Nashor': ('Debes mantener ataques entre habilidades; una rotación seguida de retirada inmediata aprovecha poco sus impactos.', 'Precisa manter ataques entre habilidades; uma rotação seguida de retirada imediata aproveita pouco os acertos.', 'Compra cuando el rival permita una cadena real de ataques desde una posición sostenible.', 'Compre quando o inimigo permitir uma sequência real de ataques de uma posição sustentável.'),
 'Creagrietas': ('Tu ventaja depende de permanecer en combate, no de entrar y salir con un único impacto.', 'Sua vantagem depende de permanecer em combate, não de entrar e sair com um único acerto.', 'Mantén la pelea solo mientras puedas repetir tu daño sin perder la herramienta defensiva del campeón.', 'Mantenha a luta apenas enquanto consegue repetir o dano sem perder a ferramenta defensiva do campeão.'),
 'Impulso Cósmico': ('Necesitas espacio después de dañar para volver a colocarte al alcance de tu siguiente habilidad.', 'Precisa de espaço depois de causar dano para voltar ao alcance da próxima habilidade.', 'Usa la movilidad después del impacto para cambiar el ángulo; no para prolongar una entrada sin recursos.', 'Use a mobilidade depois do acerto para mudar o ângulo; não para prolongar uma entrada sem recursos.'),
 'Vara de las edades': ('La compra apuesta por una pelea posterior; retrasarla pierde parte de la progresión que buscabas.', 'A compra aposta numa luta posterior; atrasar perde parte da progressão que buscava.', 'Compara el tiempo hasta la próxima disputa con la maduración del objeto antes de elegir una compra de escalado.', 'Compare o tempo até a próxima disputa com a maturação do item antes de escolher uma compra de crescimento.'),
 'Abrazo del serafín': ('Maná y supervivencia permiten repetir la rotación, pero necesitas haber preparado la carga anterior.', 'Mana e sobrevivência permitem repetir a rotação, mas precisa ter preparado o carregamento anterior.', 'Verifica carga y maná restante; el escudo no sustituye conservar la herramienta de salida.', 'Confira carga e mana restante; o escudo não substitui preservar a ferramenta de saída.'),
 'Manamune': ('La repetición de habilidades exige maná, pero el pico de daño depende de completar las cargas.', 'A repetição de habilidades exige mana, mas o pico de dano depende de completar os acúmulos.', 'Compra por el recorrido de carga y el consumo de tu campeón; no cuentes la transformación antes de verla.', 'Compre pelo caminho de carregamento e consumo do campeão; não conte a transformação antes de vê-la.'),
 'Cetro de cristal de Rylai': ('El enemigo sale de tu zona antes de recibir las siguientes aplicaciones de daño.', 'O inimigo sai da zona antes de receber as próximas aplicações de dano.', 'Usa la ralentización para mantener al objetivo en tu zona; no persigas si tu recurso de daño ya terminó.', 'Use a lentidão para manter o alvo na zona; não persiga se seu recurso de dano já terminou.'),
 'Corona de la Reina Fragmentada': ('El daño de entrada rival te elimina antes de poder usar tu herramienta defensiva.', 'O dano da entrada inimiga elimina você antes de usar sua ferramenta defensiva.', 'Evita perder la protección ante hostigamiento menor justo antes de la pelea que necesitas soportar.', 'Evite perder a proteção para pressão leve antes da luta que precisa suportar.'),
 'Eclipse': ('Puedes conectar dos acciones independientes antes de que el rival cierre el intercambio.', 'Consegue conectar duas ações independentes antes do inimigo encerrar a troca.', 'Activa la protección dentro del intercambio corto y sal antes de que la respuesta rival supere el escudo.', 'Ative a proteção na troca curta e saia antes de a resposta inimiga superar o escudo.'),
 'Cuchilla negra': ('La armadura rival exige varias aplicaciones de daño físico, no una sola entrada de daño mágico.', 'A armadura inimiga exige várias aplicações de dano físico, não uma única entrada de dano mágico.', 'Mantén aplicaciones físicas sobre el mismo objetivo antes de esperar la reducción completa de armadura.', 'Mantenha aplicações físicas no mesmo alvo antes de esperar a redução completa de armadura.'),
 'Baile de la muerte': ('Necesitas sobrevivir al daño de respuesta hasta conseguir la eliminación que permite continuar.', 'Precisa sobreviver ao dano de resposta até conseguir a eliminação que permite continuar.', 'Elige un derribo alcanzable y una salida; diferir daño no convierte una entrada aislada en segura.', 'Escolha uma eliminação alcançável e uma saída; adiar dano não torna segura uma entrada isolada.'),
 'Calibrador de Sterak': ('La ráfaga rival llega cuando ya estás comprometido en el alcance cuerpo a cuerpo.', 'A rajada inimiga chega quando você já está comprometido no alcance corpo a corpo.', 'Conserva tu habilidad de respuesta para usarla durante la protección; no vuelvas a entrar con el escudo agotado.', 'Preserve sua habilidade de resposta para usar durante a proteção; não entre outra vez com o escudo esgotado.'),
 'Hoja del rey arruinado': ('Tu acceso permite atacar repetidamente a un objetivo con mucha vida actual.', 'Seu acesso permite atacar repetidamente um alvo com muita vida atual.', 'Concentra los impactos en un objetivo alcanzable y usa la ralentización para mantener alcance sin perder la salida.', 'Concentre os acertos num alvo alcançável e use a lentidão para manter alcance sem perder a saída.'),
 'Verdugo de Krakens': ('Una cadena de ataques sobre el mismo rival permite llevar el daño hacia la fase de remate.', 'Uma sequência de ataques no mesmo inimigo permite levar o dano à fase de finalização.', 'Completa los ciclos de ataques desde cobertura; cambiar de blanco sin necesidad retrasa tu remate.', 'Complete os ciclos de ataques da cobertura; trocar de alvo sem necessidade atrasa a finalização.'),
 'Filo Infinito': ('Tu daño depende de críticos que debes acompañar con acceso a ataques seguros.', 'Seu dano depende de críticos que precisa acompanhar com acesso a ataques seguros.', 'Asegura oportunidades reales de atacar antes de invertir en amplificación de crítico; no reemplaza protección.', 'Garanta oportunidades reais de atacar antes de investir na amplificação de crítico; não substitui proteção.'),
 'Recaudadora': ('Necesitas convertir daño ya aplicado en una ejecución, no abrir sobre el tanque que conserva toda su vida.', 'Precisa converter dano já aplicado em execução, não abrir contra o tanque com vida cheia.', 'Busca el objetivo próximo al umbral de ejecución después del daño aliado, sin cruzar tu cobertura.', 'Busque o alvo próximo do limite de execução depois do dano aliado, sem atravessar sua cobertura.'),
 'Cañón de Fuego Rápido': ('La primera distancia de ataque te permite presionar sin entrar de inmediato al alcance rival.', 'A distância do primeiro ataque permite pressionar sem entrar imediatamente no alcance inimigo.', 'Aprovecha el golpe de alcance para abrir la ventana; retírate después si el alcance normal ya no es seguro.', 'Aproveite o ataque de alcance para abrir a janela; recue depois se o alcance normal não for seguro.'),
 'Huracán de Runaan': ('Existen varios blancos a alcance y tu posición permite repartir ataques sin exponerte.', 'Existem vários alvos ao alcance e sua posição permite dividir ataques sem expor você.', 'Compra por las peleas con blancos cercanos adicionales; un duelo aislado no aprovecha los proyectiles secundarios.', 'Compre por lutas com alvos adicionais próximos; um duelo isolado não aproveita os projéteis secundários.'),
 'Filoveloz de Navori': ('Los ataques durante el combate deben recuperar tus habilidades básicas para una segunda rotación.', 'Os ataques no combate precisam recuperar suas habilidades básicas para uma segunda rotação.', 'Ataca mientras la habilidad básica decisiva recarga; no cuentes reducción sobre tu definitiva.', 'Ataque enquanto a habilidade básica decisiva recarrega; não conte redução na ultimate.'),
 'Flechas de los Yun Tal': ('Tu progresión necesita ataques continuados y una ventana donde puedas aprovechar la ráfaga de velocidad.', 'Sua progressão precisa de ataques contínuos e uma janela para aproveitar a rajada de velocidade.', 'Abre la ráfaga desde protección y prepara los ataques posteriores; no gires para perseguir sin blancos seguros.', 'Abra a rajada da proteção e prepare os ataques seguintes; não vire para perseguir sem alvos seguros.'),
 'Sanguinaria': ('Tienes acceso a ataques y necesitas recuperar vida entre intercambios sin abandonar la presión.', 'Tem acesso a ataques e precisa recuperar vida entre trocas sem abandonar a pressão.', 'Recupera vida sobre blancos seguros antes de la siguiente disputa; el robo de vida no funciona mientras estés controlado.', 'Recupere vida em alvos seguros antes da próxima disputa; o roubo de vida não funciona enquanto estiver controlado.'),
 'Bailarín Espectral': ('Necesitas conservar alcance después de varios ataques, no únicamente aumentar el primer impacto.', 'Precisa manter alcance depois de vários ataques, não apenas aumentar o primeiro acerto.', 'Construye las acumulaciones atacando desde cobertura y usa el movimiento para conservar distancia.', 'Construa os acúmulos atacando da cobertura e use o movimento para manter distância.'),
 'Final del ingenio': ('El daño mágico rival coincide con una pelea donde puedes mantener ataques.', 'O dano mágico inimigo coincide com uma luta em que consegue manter ataques.', 'La resistencia acompaña los ataques; si no puedes atacar, prioriza la respuesta defensiva al control o a la ráfaga.', 'A resistência acompanha os ataques; se não consegue atacar, priorize a resposta defensiva ao controle ou à rajada.'),
 'El final': ('Puedes sostener suficientes ataques para preparar defensa y penetración durante el mismo combate.', 'Consegue sustentar ataques suficientes para preparar defesa e penetração no mesmo combate.', 'Entra con acceso a varios ataques; no atribuyas todas las acumulaciones a tu primer golpe.', 'Entre com acesso a vários ataques; não atribua todos os acúmulos ao primeiro golpe.'),
 'Recuerdos de Lord Dominik': ('La vida adicional y la armadura de los objetivos alcanzables están absorbiendo tus ataques.', 'A vida adicional e a armadura dos alvos alcançáveis estão absorvendo seus ataques.', 'Elige penetración por el rival que realmente bloquea tu daño; no por un tanque al que nunca necesitas golpear.', 'Escolha penetração pelo inimigo que realmente bloqueia seu dano; não por um tanque que nunca precisa atingir.'),
 'Rencor de Serylda': ('Necesitas atravesar armadura y mantener al rival en el alcance de tus siguientes habilidades.', 'Precisa atravessar armadura e manter o inimigo ao alcance das próximas habilidades.', 'Usa la ralentización para asegurar la siguiente habilidad; no la conviertas en permiso para perseguir sin recursos.', 'Use a lentidão para garantir a próxima habilidade; não transforme em permissão para perseguir sem recursos.'),
 'Colmillo de serpiente': ('Los escudos visibles absorben tu ventana de daño contra el objetivo prioritario.', 'Os escudos visíveis absorvem sua janela de dano contra o alvo prioritário.', 'Aplica daño durante el escudo que necesitas reducir; no adelantes esta compra por un escudo que no decide la pelea.', 'Aplique dano durante o escudo que precisa reduzir; não antecipe a compra por um escudo que não decide a luta.'),
 'Filo de la noche': ('Un control puntual interrumpe tu acceso antes de alcanzar al objetivo.', 'Um controle pontual interrompe seu acesso antes de alcançar o alvo.', 'Conserva el bloqueo hasta tu entrada; un proyectil menor puede consumirlo antes de la habilidad decisiva.', 'Preserve o bloqueio até sua entrada; um projétil menor pode consumir antes da habilidade decisiva.'),
 'Filo fantasmal de Youmuu': ('Tu ruta de aproximación necesita llegar antes de que el objetivo reciba cobertura aliada.', 'Sua rota de aproximação precisa chegar antes de o alvo receber cobertura aliada.', 'Usa la movilidad para el ángulo de entrada y retirada; no llegues antes que el seguimiento de tu equipo.', 'Use a mobilidade para o ângulo de entrada e retirada; não chegue antes do acompanhamento da equipe.'),
 'Filoscuro de Draktharr': ('Tu secuencia necesita aprovechar un acceso desde niebla en vez de una pelea frontal prolongada.', 'Sua sequência precisa aproveitar acesso pela névoa em vez de uma luta frontal prolongada.', 'Prepara el acceso fuera de visión y el primer blanco frágil; si el rival ya te ve, cambia el ángulo.', 'Prepare o acesso fora de visão e o primeiro alvo frágil; se o inimigo já vê você, mude o ângulo.'),
 'Rompecascos': ('La presión lateral exige una ruta de retirada cuando el rival envíe una segunda respuesta.', 'A pressão lateral exige uma rota de retirada quando o inimigo enviar uma segunda resposta.', 'Compra por una tarea lateral sostenida; cuenta rivales desaparecidos antes de comprometer la siguiente torre.', 'Compre por uma tarefa lateral sustentada; conte inimigos desaparecidos antes de comprometer a próxima torre.'),
 'Hidra titánica': ('Necesitas convertir ataques y vida acumulada en presión sobre varios blancos cercanos.', 'Precisa converter ataques e vida acumulada em pressão contra vários alvos próximos.', 'Alinea el ataque con los blancos secundarios y conserva la habilidad defensiva para después de acercarte.', 'Alinhe o ataque com alvos secundários e preserve a habilidade defensiva depois de aproximar.'),
 'Ángel de la guarda': ('La entrada puede terminar en muerte, pero solo existe valor si tus aliados pueden cubrir el punto de regreso.', 'A entrada pode terminar em morte, mas só tem valor se os aliados cobrirem o ponto de retorno.', 'Comprueba quién protegerá la reaparición antes de entrar; resucitar aislado no abre una segunda rotación.', 'Confira quem protegerá o retorno antes de entrar; ressuscitar isolado não abre uma segunda rotação.'),
 'Fauces de Malmortius': ('La ráfaga mágica interrumpe tu daño físico antes de completar el intercambio.', 'A rajada mágica interrompe seu dano físico antes de completar a troca.', 'Aprovecha la protección para cerrar tu secuencia o retirarte; no para volver a recibir toda la rotación mágica.', 'Aproveite a proteção para terminar a sequência ou recuar; não para receber outra rotação mágica inteira.'),
 'Arcoescudo Inmortal': ('Una ráfaga te impide mantener ataques y necesitas protección al cruzar el umbral de vida.', 'Uma rajada impede manter ataques e precisa de proteção ao cruzar o limite de vida.', 'Usa el escudo para volver a cobertura y continuar atacando; no esperes que cubra otro intercambio cuando esté en recarga.', 'Use o escudo para voltar à cobertura e continuar atacando; não espere que cubra outra troca durante a recarga.'),
}

# Defensive and support purchases have explicit duties, not a universal damage paragraph.
EXTRA_POLICIES = {
 'Botas blindadas': ('Aproximarte frente a ataques físicos conservando tu control para responder después.', 'Aproximar diante de ataques físicos preservando seu controle para responder depois.'),
 'Avance blindado': ('Sostener la movilidad necesaria para entrar y salir frente a la presión física.', 'Sustentar a mobilidade necessária para entrar e sair diante da pressão física.'),
 'Botas de maná': ('Mantener maná para la siguiente rotación sin gastar tu habilidad de protección para acercarte.', 'Manter mana para a próxima rotação sem gastar sua habilidade de proteção para aproximar.'),
 'Botas del lanzahechizos': ('Convertir una segunda habilidad disponible en presión desde un ángulo seguro.', 'Converter uma segunda habilidade disponível em pressão de um ângulo seguro.'),
 'Botas dinámicas': ('Llegar al objetivo frágil y conservar una ruta de retirada después de tu daño físico.', 'Chegar ao alvo frágil e preservar uma rota de retirada depois do dano físico.'),
 'Botas inmortales': ('Sostener tu presencia cerca del objetivo sin entregar la salida por perseguir un impacto adicional.', 'Sustentar sua presença perto do alvo sem entregar a saída para perseguir um acerto adicional.'),
 'Botas jonias de la lucidez': ('Preparar una segunda habilidad básica y un hechizo disponible para la siguiente disputa.', 'Preparar uma segunda habilidade básica e um feitiço disponível para a próxima disputa.'),
 'Botas quebrantarmaduras': ('Mantener alcance para aplicar tu daño físico sobre el rival que absorbe la primera rotación.', 'Manter alcance para aplicar seu dano físico no inimigo que absorve a primeira rotação.'),
 'Grebas codiciosas': ('Recuperar vida con ataques seguros antes de volver a disputar el alcance del rival.', 'Recuperar vida com ataques seguros antes de disputar outra vez o alcance inimigo.'),
 'Grebas de berserker': ('Mantener varios ataques durante la ventana de tu habilidad sin cruzar la protección aliada.', 'Manter vários ataques na janela da habilidade sem atravessar a proteção aliada.'),
 'Grebas de metal': ('Conservar distancia de respuesta frente al daño físico que llega durante tu entrada.', 'Preservar distância de resposta diante do dano físico durante sua entrada.'),
 'Lucidez carmesí': ('Repetir tu habilidad decisiva sin consumir todos los recursos antes del segundo intercambio.', 'Repetir sua habilidade decisiva sem consumir todos os recursos antes da segunda troca.'),
 'Armadura de Warmog': ('Regresar al frente después de recuperar vida sin sacrificar otro regreso a base.', 'Voltar à linha de frente depois de recuperar vida sem exigir outro retorno à base.'),
 'Bastón de aguas fluidas': ('Curar o proteger al aliado que realmente convertirá la mejora en su siguiente rotación.', 'Curar ou proteger o aliado que realmente converterá a melhoria na próxima rotação.'),
 'Bendición de Mikael': ('Reservar la limpieza para el control que detiene al aliado prioritario.', 'Reservar a limpeza para o controle que impede o aliado prioritário.'),
 'Canción de batalla de Shurelya': ('Sincronizar la aceleración con la entrada o retirada del grupo completo.', 'Sincronizar a aceleração com a entrada ou retirada do grupo inteiro.'),
 'Convergencia de Zeke': ('Permanecer al alcance del aliado que pueda golpear después de tu iniciación.', 'Permanecer ao alcance do aliado que consiga atacar depois da iniciação.'),
 'Coraza del muerto': ('Llegar al ángulo de control sin gastar antes tu habilidad de salida.', 'Chegar ao ângulo de controle sem gastar antes sua habilidade de saída.'),
 'Coraza dual purpúrea': ('Preparar defensa durante una pelea que sí permita permanecer cerca de campeones.', 'Preparar defesa numa luta que permita permanecer perto de campeões.'),
 'Corazón de acero': ('Conseguir el golpe de acumulación sin perder el intercambio por forzar distancia.', 'Conseguir o ataque de acúmulo sem perder a troca por forçar distância.'),
 'Corazón de hielo': ('Mantener a los atacantes dentro de tu radio defensivo sin separarte de tu retaguardia.', 'Manter os atacantes no seu raio defensivo sem separar da retaguarda.'),
 'Corona abrasadora': ('Mantener las aplicaciones de quemadura sobre la primera línea que puedas alcanzar.', 'Manter aplicações de queimadura na linha de frente que consegue alcançar.'),
 'Eco armónico': ('Aplicar curaciones y escudos donde haya un segundo aliado que pueda recibir la extensión.', 'Aplicar curas e escudos onde haja um segundo aliado que possa receber a extensão.'),
 'Escudo reliquia': ('Ejecutar el súbdito con una carga disponible y acompañar al tirador sin quitarle ingresos.', 'Executar a tropa com uma carga disponível e acompanhar o atirador sem tirar sua renda.'),
 'Fuerza de la naturaleza': ('Sostener la entrada contra aplicaciones mágicas repetidas y salir cuando termine tu recurso defensivo.', 'Sustentar a entrada contra aplicações mágicas repetidas e sair quando terminar seu recurso defensivo.'),
 'Hoz espectral': ('Cobrar la carga con hostigamiento seguro sin adelantar tu posición fuera de la cobertura del tirador.', 'Receber a carga com pressão segura sem avançar fora da cobertura do atirador.'),
 'Incensario ardiente': ('Proteger al aliado que pueda mantener ataques durante la mejora, no al que ya se retira.', 'Proteger o aliado que consiga manter ataques durante a melhoria, não aquele que já recua.'),
 'Malla de espinas': ('Recibir los ataques del rival que necesita curarse sin que la provocación aleje a tu equipo.', 'Receber ataques do inimigo que precisa curar sem que a provocação afaste a equipe.'),
 'Mandato imperial': ('Aplicar control cuando el equipo pueda concentrar daño durante la marca.', 'Aplicar controle quando a equipe possa concentrar dano durante a marca.'),
 'Medallón de los Solari de Hierro': ('Agrupar la protección antes de la ráfaga que llegue a varios aliados.', 'Agrupar a proteção antes da rajada que atingir vários aliados.'),
 'Máscara abisal': ('Permanecer en el alcance donde tus aliados de daño mágico puedan aprovechar tu presencia.', 'Permanecer no alcance onde seus aliados de dano mágico possam aproveitar sua presença.'),
 'Precisión infalible': ('Elegir una línea de daño a distancia que permita repetir habilidades sobre un blanco alcanzable.', 'Escolher uma linha de dano à distância que permita repetir habilidades num alvo alcançável.'),
 'Presagio de Randuin': ('Entrar frente al daño crítico que realmente golpea tu posición y proteger a los aliados cercanos.', 'Entrar diante do dano crítico que realmente atinge sua posição e proteger aliados próximos.'),
 'Promesa de caballero': ('Vincularte al aliado al que puedes acompañar y proteger durante su ventana de daño.', 'Vincular ao aliado que consegue acompanhar e proteger durante sua janela de dano.'),
 'Redención': ('Colocar la zona donde tus aliados podrán permanecer cuando llegue la curación.', 'Colocar a zona onde os aliados conseguirão permanecer quando a cura chegar.'),
 'Velo del amanecer': ('Usar tu control dentro del alcance que permita aprovechar la protección y la revelación.', 'Usar seu controle no alcance que permita aproveitar a proteção e revelação.'),
 'Égida de fuego solar': ('Mantener al enemigo cerca durante tu cadena de control para aprovechar el daño de proximidad.', 'Manter o inimigo perto durante sua sequência de controle para aproveitar o dano de proximidade.'),
}

RUNE_POLICIES = {
 'Aery': ('Alterna hostigamiento seguro y protección según quién recibirá la siguiente respuesta.', 'Alterne pressão segura e proteção conforme quem receberá a próxima resposta.'),
 'Banda de Maná': ('Consigue la carga sobre el campeón cuando puedas golpear sin gastar la habilidad de salida.', 'Consiga o acúmulo no campeão quando puder acertar sem gastar a habilidade de saída.'),
 'Brutal': ('Busca ataques sostenidos desde cobertura; una única habilidad a distancia no aprovecha este plan.', 'Busque ataques sustentados da cobertura; uma única habilidade à distância não aproveita esse plano.'),
 'Capa del Nimbo': ('Elige el rumbo de salida antes de gastar el hechizo; usa la aceleración para cambiar el ángulo de respuesta.', 'Escolha a direção de saída antes de gastar o feitiço; use a aceleração para mudar o ângulo da resposta.'),
 'Celeridad': ('Aprovecha tu aceleración para repetir daño desde el borde de alcance y volver a cobertura.', 'Aproveite sua aceleração para repetir dano da borda do alcance e voltar à cobertura.'),
 'Colección de Globos Oculares': ('Participa en derribos que permitan salir con vida; perseguir una asistencia aislada retrasa tu siguiente oleada o campamento.', 'Participe de eliminações que permitam sair vivo; perseguir uma assistência isolada atrasa a próxima onda ou campo.'),
 'Cometa Arcano': ('Lanza el hostigamiento cuando el rival tenga su trayectoria fijada por un último golpe o una ralentización.', 'Lance a pressão quando a trajetória inimiga estiver fixada pelo golpe final ou por uma lentidão.'),
 'Compás Letal': ('Prepara la posición para una cadena de ataques; no entregues vida intentando completar cargas sin protección.', 'Prepare a posição para uma sequência de ataques; não entregue vida tentando completar acúmulos sem proteção.'),
 'Conquistador': ('Mantén la cadena de ataques y habilidades sobre una pelea sostenible; retirarte después de un golpe no aprovecha el combate largo.', 'Mantenha a sequência de ataques e habilidades numa luta sustentável; recuar após um golpe não aproveita a luta longa.'),
 'Cosecha Oscura': ('Reserva el impacto para un objetivo ya desgastado que puedas alcanzar sin sacrificar tu salida.', 'Reserve o acerto para um alvo já desgastado que consiga alcançar sem sacrificar a saída.'),
 'Demoler': ('Prepara la oleada y la carga junto a la torre antes de golpear; retírate si la respuesta rival llega antes del impacto.', 'Prepare a onda e a carga junto da torre antes de atacar; recue se a resposta inimiga chegar antes do acerto.'),
 'Electrocutar': ('Completa tres acciones válidas dentro del intercambio corto y sal antes de absorber la respuesta prolongada.', 'Complete três ações válidas na troca curta e saia antes de receber a resposta prolongada.'),
 'Fortalecimiento': ('Sincroniza la defensa con el control que abre tu entrada y la respuesta que llega inmediatamente después.', 'Sincronize a defesa com o controle que abre sua entrada e a resposta imediatamente depois.'),
 'Fuente de Vida': ('Marca con tu control a un enemigo que los aliados realmente puedan atacar durante la protección.', 'Marque com seu controle um inimigo que os aliados realmente consigam atacar durante a proteção.'),
 'Fuerzas Renovadas': ('Permite que la recuperación termine entre hostigamientos antes de comprometer otra entrada.', 'Permita a recuperação terminar entre pressões antes de comprometer outra entrada.'),
 'Garras del Inmortal': ('Prepara el golpe mientras estás en combate y entra solo para un ataque seguro antes de volver a distancia.', 'Prepare o golpe enquanto está em combate e entre apenas para um ataque seguro antes de voltar à distância.'),
 'Golpe Bajo': ('Aplica tu control o ralentización antes del daño que lo aprovecha; no inviertas la secuencia por apresurarte.', 'Aplique seu controle ou lentidão antes do dano que aproveita; não inverta a sequência pela pressa.'),
 'Golpe de Gracia': ('Concentra el cierre sobre el blanco debilitado alcanzable; no cruces la primera línea por un remate inseguro.', 'Concentre a finalização no alvo enfraquecido alcançável; não atravesse a linha de frente por uma finalização insegura.'),
 'Guardián': ('Mantén la distancia de protección al aliado que recibe la entrada; estar lejos pierde la ventana defensiva.', 'Mantenha a distância de proteção do aliado que recebe a entrada; estar longe perde a janela defensiva.'),
 'Hextello': ('Prepara la canalización fuera de visión para cambiar el ángulo de entrada; no canalices delante de una interrupción.', 'Prepare a canalização fora de visão para mudar o ângulo da entrada; não canalize diante de uma interrupção.'),
 'Impacto Repentino': ('Aplica el daño después del desplazamiento o de salir del sigilo; solo usa esta elección si tu campeón activa esa condición de forma habitual.', 'Aplique o dano depois do deslocamento ou de sair da invisibilidade; use esta escolha apenas se o campeão ativar essa condição habitualmente.'),
 'Irrupción de Fase': ('Completa la activación antes de usar la aceleración para retirarte o seguir el blanco; no abandones la salida por una cuarta acción.', 'Complete a ativação antes de usar a aceleração para recuar ou seguir o alvo; não abandone a saída por uma quarta ação.'),
 'Leyenda: Linaje': ('Recupera vida con ataques seguros entre disputas; no confíes en el robo de vida durante control enemigo.', 'Recupere vida com ataques seguros entre disputas; não confie no roubo de vida durante controle inimigo.'),
 'Leyenda: Presteza': ('El valor llega al sostener ataques durante tus ventanas de habilidad; mantén un blanco seguro antes de invertir en velocidad.', 'O valor chega ao sustentar ataques nas janelas de habilidade; mantenha um alvo seguro antes de investir em velocidade.'),
 'Leyenda: Velocidad': ('La progresión sirve a tus ataques repetidos; convierte cada derribo seguro en presión sin romper tu cobertura.', 'A progressão serve aos ataques repetidos; converta cada eliminação segura em pressão sem romper sua cobertura.'),
 'Orbe Anulador': ('Conserva tu salida para usarla junto a la protección mágica; el escudo no niega el control que siga al daño.', 'Preserve sua saída para usar junto da proteção mágica; o escudo não nega o controle depois do dano.'),
 'Pies Veloces': ('Prepara el ataque con vigor sobre un blanco seguro y usa la aceleración para salir del intercambio.', 'Prepare o ataque energizado num alvo seguro e use a aceleração para sair da troca.'),
 'Piroláser': ('Usa hostigamientos con una retirada preparada; no añadas un ataque inseguro solo para extender el daño.', 'Use pressão com uma retirada preparada; não acrescente um ataque inseguro apenas para estender o dano.'),
 'Primer Golpe': ('Inicia tú el daño desde un ángulo que el rival no pueda contestar primero; si ya te golpeó, espera otra ventana.', 'Inicie você o dano de um ângulo que o inimigo não consiga responder primeiro; se já atingiu você, espere outra janela.'),
 'Revestimiento de Huesos': ('Evita perder la protección a un golpe menor antes de la ráfaga rival; cambia distancia mientras vuelve a estar disponible.', 'Evite perder a proteção para um golpe leve antes da rajada inimiga; mude a distância enquanto volta a ficar disponível.'),
 'Revitalizar': ('Protege o cura al blanco que va a recibir la siguiente respuesta, en vez de gastar la mejora sobre alguien ya seguro.', 'Proteja ou cure o alvo que receberá a próxima resposta, em vez de gastar a melhoria em alguém já seguro.'),
 'Se Avecina Tormenta': ('Tu plan requiere llegar a la pelea posterior sin perder oleadas por duelos que no compensan el riesgo.', 'Seu plano exige chegar à luta posterior sem perder ondas por duelos que não compensam o risco.'),
 'Soberano Gélido': ('Fuerza la trayectoria rival con tu control y aprovecha la zona para que el equipo pueda mantener alcance.', 'Force a trajetória inimiga com seu controle e aproveite a zona para a equipe manter alcance.'),
 'Sobrecrecimiento': ('Recoge la progresión cerca de unidades que mueren sin abandonar la tarea que protege al equipo.', 'Recolha a progressão perto de unidades que morrem sem abandonar a tarefa que protege a equipe.'),
 'Tirano': ('Prepara el primer daño para llevar al rival al umbral y concentra el siguiente impacto sin sacrificar la salida.', 'Prepare o primeiro dano para levar o inimigo ao limite e concentre o próximo acerto sem sacrificar a saída.'),
 'Trascendencia': ('La aceleración sirve a una segunda habilidad segura; revisa si tendrás recursos y alcance antes de prolongar la pelea.', 'A aceleração serve a uma segunda habilidade segura; confira recursos e alcance antes de prolongar a luta.'),
 'Triunfo': ('Busca un primer derribo alcanzable y usa la recuperación para reposicionar antes de perseguir el segundo.', 'Busque uma primeira eliminação alcançável e use a recuperação para reposicionar antes de perseguir a segunda.'),
 'Último Esfuerzo': ('Continúa con poca vida solo si puedes usar tu herramienta defensiva y cerrar el objetivo antes de su respuesta.', 'Continue com pouca vida apenas se consegue usar a ferramenta defensiva e finalizar antes da resposta inimiga.'),
}

SPELL_POLICIES = {
 'Aplastar': ('Coordina el daño visible de Castigo con tu habilidad de remate; no lo gastes antes de la ventana de disputa.', 'Combine o dano visível de Golpear com sua habilidade de finalização; não gaste antes da janela de disputa.'),
 'Barrera': ('Actívala cuando llegue la ráfaga que no puedes esquivar y aprovecha la protección para terminar tu secuencia o salir.', 'Ative quando chegar a rajada que não consegue esquivar e aproveite a proteção para terminar a sequência ou sair.'),
 'Curar': ('Mantente cerca del aliado que recibirá el beneficio; decide el momento por el daño entrante y la ruta de retirada.', 'Fique perto do aliado que receberá o benefício; escolha o momento pelo dano recebido e pela rota de retirada.'),
 'Extenuación': ('Aplica la reducción al atacante cuando comprometa su ráfaga, no mientras todavía se aproxima sin gastar daño.', 'Aplique a redução no atacante quando comprometer sua rajada, não enquanto aproxima sem gastar dano.'),
 'Fantasmal': ('Actívalo antes del recorrido de persecución o retirada y usa tu control para que el rival no corte la cadena.', 'Ative antes do percurso de perseguição ou retirada e use seu controle para o inimigo não cortar a sequência.'),
 'Limpiar': ('Responde al control que realmente niega tu salida; confirma que el efecto observado sea eliminable antes de confiar en este hechizo.', 'Responda ao controle que realmente nega sua saída; confirme se o efeito observado pode ser removido antes de confiar neste feitiço.'),
 'Prender': ('Sincroniza daño y heridas graves con el intento rival de curarse durante tu ventana de remate.', 'Sincronize dano e Feridas Dolorosas com a tentativa inimiga de curar durante sua janela de finalização.'),
}

def element(champion, lane_name, name, kind, pt=False, display_name=None):
    risk, rule = profile(champion, pt)
    if name in ('Destello', 'Flash'):
        return ''
    steps = rule.split('; ', 1)
    anchor = steps[0].rstrip('.')
    continuation = steps[-1] if len(steps) > 1 else rule
    if kind == 'item':
        if name in ITEM_POLICIES:
            values = ITEM_POLICIES[name]
            need, action = values[int(pt)], values[2 + int(pt)]
        elif name in EXTRA_POLICIES:
            action = EXTRA_POLICIES[name][int(pt)]
            need = ('La tarea de esta compra es ' if not pt else 'A tarefa desta compra é ') + action[0].lower() + action[1:]
        elif 'bota' in name.lower() or name in ('Grebas codiciosas', 'Avance blindado', 'Avance mercurial', 'Lucidez carmesí', 'Grebas berserker'):
            need = 'La movilidad debe permitir ejecutar tu condición sin consumir la herramienta de salida.' if not pt else 'A mobilidade deve permitir executar sua condição sem consumir a ferramenta de saída.'
            action = 'Elige la defensa por el daño o control que recibes al acercarte, y conserva tu recurso para volver a cobertura.' if not pt else 'Escolha a defesa pelo dano ou controle ao aproximar e preserve seu recurso para voltar à cobertura.'
        else:
            raise AssertionError(('Item lacks authored policy', name))
    else:
        table = RUNE_POLICIES if kind == 'rune' else SPELL_POLICIES
        action = table[name][int(pt)]
        need = risk
    me = (champion.get('namePt') or champion['name'].replace('Nunu y Willump', 'Nunu e Willump')) if pt else champion['name']
    titles = ('Diagnóstico do erro/situação','Decisão Soberano','Micro e Macro detalhe','Regra aplicável') if pt else ('Diagnóstico del error/situación','Decisión Soberano','Micro y Macro detalle','Regla aplicable')
    return '\n'.join(f'{t}: {v}' for t, v in zip(titles, (
        f'{me} · {lane_name} · {display_name or name}. {need}', action, anchor + '.', continuation[0].upper() + continuation[1:])))
