"""Generate the offline Kotlin registry from the bilingual component JSON; --check rejects drift."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'app/src/main/assets/wild_rift_component_items.json'
DESTINATION = ROOT / 'app/src/main/java/com/example/data/WildRiftComponentItemsData.kt'

def kotlin(value):
    return json.dumps(value, ensure_ascii=False).replace('$', '\\$')

def generate():
    data = json.loads(SOURCE.read_text())
    expected = ['LUCHADOR', 'ASESINO', 'TIRADOR', 'MÁGICO', 'DEFENSA', 'APOYO']
    assert list(data['secciones']) == expected
    objects, levels, memberships = {}, {}, {}
    for section, groups in data['secciones'].items():
        assert list(groups) == ['Básico', 'Nivel Medio']
        memberships[section] = {}
        for level, entries in groups.items():
            assert len({entry['id'] for entry in entries}) == len(entries)
            memberships[section][level] = [entry['id'] for entry in entries]
            for entry in entries:
                identity = entry['id']
                assert identity not in objects or objects[identity] == entry, f'Conflicting repeated object: {identity}'
                assert identity not in levels or levels[identity] == level
                assert entry['coste_oro'] > 0 and entry['nombre'] and entry['nombre_pt']
                assert len(entry['estadisticas']) == len(entry['estadisticas_pt'])
                objects[identity], levels[identity] = entry, level
    output = ['// Generated by tools/generate-component-items.py. Edit the JSON source.',
              'package com.example.data', '', 'import com.example.model.WildRiftItem', '',
              'object WildRiftComponentItemsData {', '    val items: List<WildRiftItem> = listOf(']
    for identity, entry in objects.items():
        def effect(language):
            return '\n'.join((row['nombre'+language] + ': ' if row['nombre'+language] else '') + row['descripcion'+language] for row in entry['efectos'])
        output += ['        WildRiftItem(',
                   f'            id = {kotlin(identity)}, name = {kotlin(entry["nombre"])}, namePt = {kotlin(entry["nombre_pt"])},',
                   f'            category = {kotlin(levels[identity])}, goldCost = {entry["coste_oro"]},',
                   f'            stats = {kotlin(" • ".join(entry["estadisticas"]))},',
                   f'            statsPt = {kotlin(" • ".join(entry["estadisticas_pt"]))},',
                   f'            passive = {kotlin(effect(""))},',
                   f'            passivePt = {kotlin(effect("_pt"))}, iconUrl = ""', '        ),']
    output += ['    )', '', '    val sectionItemIds: Map<String, Map<String, List<String>>> = mapOf(']
    labels = ['Luchador', 'Asesino', 'Tirador', 'Mágico', 'Defensa', 'Apoyo']
    for section, label in zip(expected, labels):
        output.append(f'        {kotlin(label)} to mapOf(')
        for level, ids in memberships[section].items():
            output.append(f'            {kotlin(level)} to listOf({", ".join(map(kotlin, ids))}),')
        output.append('        ),')
    output += ['    )', '', '    private val byId = items.associateBy { it.id }', '',
               '    fun getItems(section: String, level: String): List<WildRiftItem> =',
               '        sectionItemIds.entries.firstOrNull { it.key.equals(section, ignoreCase = true) }',
               '            ?.value?.entries?.firstOrNull { it.key.equals(level, ignoreCase = true) }',
               '            ?.value.orEmpty().map { byId.getValue(it) }', '}', '']
    return '\n'.join(output)

if __name__ == '__main__':
    result = generate()
    if '--check' in sys.argv:
        assert DESTINATION.read_text() == result, 'Component registry drift; run tools/generate-component-items.py'
        print('COMPONENT_CATALOG: six sections; repeated objects identical; generated Kotlin matches JSON')
    else:
        DESTINATION.write_text(result)
